### ISSUE TITLE
Formatting DATA deletes internal SD?

### ISSUE THREAD

**Issue by JPT77** [TeamWin/Team-Win-Recovery-Project#1083]
Well... Naming is a little bit odd in Android?
DATA is Android-App-Data, it's a directory on Internal SD, isn't it?
So why do you format DATA instead of IntSD? and why does this delete IntSD?
When formatting DATA/IntSD please warn that the encryption key of ExtSD is stored in DATA and thus backups stored on ExtSD won't be readable any more...

**Comment by Dees-Troy** [comment]
We discussed this topic as a team and came to the conclusion that the existing warning message should be sufficient. A factory reset (format data) on a stock Android device would also cause the user to lose access to the encrypted contents of their adopted storage. The warning message indicates that you will lose all of your pictures, etc. An adopted sdcard in Android is more or less considered part of the internal storage.

This is a bit of a corner case because you're the first person to complain about this issue since we implemented adopted storage in TWRP. We can't code around every potential issue. Sorry.

**Comment by JPT77** [comment]
Ok. And your answer to the first point? Unclear usage of DATA: Is data the IntSD partition or the Android Data? Please use eg "Data partition including IntSD" when formatting and "Android Data" for backup and restore. Then the message "not backing up IntSD" would be obsolete.

**Comment by that1** [comment]
Yes, naming is a little bit odd in Android when it comes to storage.

The main partitions in an Android system are /system and /data. /system contains the OS and is read only in regular use (so some call it "ROM"), and /data contains all user data. Including the emulated SD card, also known as "Internal Storage", and including the key for the adopted real SD card, which is designed (by Google) to work as a seamless extension of your internal /data partition. There is no "IntSD partition" that you could format separately.
