### ISSUE TITLE
I9300, TWRP 2.4.1.1, firmware upgrade, missing /system/csc

### ISSUE THREAD

**Issue by qwerty22** [TeamWin/Team-Win-Recovery-Project#115]
During the firmware upgrade from I9300XXELL4 (SER) to I9300XXEMB2 (SER) without ODIN Recovery options (without flashing stock recovery.img), if TWRP 2.4.1.1 is installed, the catalog /system/csc has been removed but not copyed from new firmware.

Not tested on TWRP 2.4.2.0

Sorry for my English

**Comment by qwerty22** [comment]
TWRP 2.4.2.0 - the same result - missing /system/csc.

**Comment by bigbiff** [comment]
Can you provide your backup and restore logs?

**Comment by qwerty22** [comment]
Logs are not saved, sorry.

Please note that this does not backup or restore operation - this is a firmware flash operation with sec_csc.zip file. Where in this log must be stored?

**Comment by bigbiff** [comment]
So you are installing this zip through the install function?

**Comment by Dees-Troy** [comment]
Can you link the sec_csc.zip file so that we can take a look at it? Is this a custom ROM or an official update from Samsung?

**Comment by qwerty22** [comment]
No, I`m not installing sec_csc.zip through the install function. 

It is official update from Samsung - I9300XXEMB2 (SER).
List of files:
1. cache.img\recovery/sec_csc.zip
2. cache.img\recovery/command:
--update_package=CACHE:recovery/sec_csc.zip
--carry_out=csc_home
--wipe_cache 

http://fcpm.ru/temp/sec_csc.zip
cache.img: http://fcpm.ru/temp/I9300XXEMB2_SER_CSC.rar

**Comment by qwerty22** [comment]
Steps to reproduce the problem:
1. Install TWRP
2. Get any I9300 official update from Samsung.
3. Rename I9300_.tar.md5 to I9300_.tar
4. Remove recovery.img from I9300*.tar
5. From I9300 run `ls /system/csc > csc_before.txt`
6. Flash firmware (Odin/mobile Odin/Heimdall flasher etc).
7. From I9300 run `ls /system/csc > csc_after.txt`
8. Compare csc_before.txt and csc_after.txt

**Comment by bigbiff** [comment]
Odin overwrites all files on the phone in system. I am not sure I understand how twrp is related to this.

**Comment by qwerty22** [comment]
Odin/mobile Odin/Heimdall sends all firmware files to /cache for processing recovery. Recovery process: 
system.img - dd method. As resault - SYSTEM partition, and /system directory.
cache.img - copyed method. As resault - /system/csc directory on SYSTEM partition.

Thus, Odin not overwrite files on the phone. Odin only controls overwriting files on the phone. Overwrites - recovery.

**Comment by qwerty22** [comment]
Example TWRP 2.4.4.0:
1. #ls /system/csc
   CAC
   RTL
   SEK
   SER
   SKZ
   common
   contents.db 
   etc.
2. mobile Odin settings http://i51.fastpic.ru/big/2013/0318/bc/4ec08e3d9da3b7658505c8817f3cfabc.png
3. "DD" step http://i52.fastpic.ru/big/2013/0318/e1/8f8da658766482cc9c45d393a03b64e1.jpg
4. "Copy" step http://i53.fastpic.ru/big/2013/0318/be/df4c0f6f607f090a0eddd34125a86dbe.jpg
   (Invalid command argument)
5. #ls /system/csc
   No search file or directory

Step 4 - TWRP bug.

**Comment by Dees-Troy** [comment]
This zip doesn't mount /system before it copies files to /system. The files are getting copied, but since /system isn't mounted they get copied to ramdisk instead of to the emmc chip.

We will not mount system during boot of TWRP. There's unfortunately a large number of ROMs out there that do not unmount /system before formatting /system which causes problems. You will need to update the zip's updater-script to mount system first if you want to be able to install it using TWRP.

**Comment by qwerty22** [comment]
> This zip doesn't mount /system

I use the official firmware.
This is the updater-script is found in all Samsung firmware. This is a script from the official firmware.
This problem does not have stock recovery.

**Comment by Dees-Troy** [comment]
Doesn't matter who made it or if it works with stock recovery. We generally don't recommend installing official updates from your manufacturer if you're using a modified device or with any custom recovery because of the potential for the manufacturer to have modified their recovery. Manufacturers aren't required to release source code for their customized versions of AOSP recovery, so if they make some changes, our custom recoveries may not be able to support those changes. Also, OTA updates are usually incremental, that is they may patch changes to an existing file to update it instead of replacing the file. Modifications that you may have made can break the OTA update.

Further, just because a major manufacturer does something doesn't make it correct. In Samsung's case, see emmc_cap_erase bug that still isn't fixed in official OTA images that can easily brick even a stock device.

You can manually install this zip by mounting system first on the mount page and then choose to install it. This issue will not be "fixed" in any official TWRP build because it will create a lot of other problems.

**Comment by expresspotato** [comment]
How is this closed?

So basically, my carrier apps (My Account, Bell TV etc), enabling of LTE+, VoLTE etc are all gone because I install TWRP? Without the CSC folder the phone is clueless on certain things. 

I get that people shouldn't be doing OTA updates, but that doesn't excuse the deleting of the original CSC.

New Note 5 here, installed TWRP and lost a whole bunch of functionality. I don't see how its any of TWRP's business to delete the csc... I just wanted a great backup and restore app.
