### ISSUE TITLE
TWRP-3.2.1-0 Pixel 2 XL Feb Security cannot decrypt

### ISSUE THREAD

**Issue by bggold** [TeamWin/Team-Win-Recovery-Project#1169]
Just updated to Feb security update on Pixel 2 xl and pattern is not accepted after booting twrp-3.2.1.0

Thanks

**Comment by Bluglug** [comment]
Same issue on the original Pixel (sailfish) as well.

Updated to Feb 5, 2018 Security patch and installed twrp 3.2.1.0.

I tested both Pattern and PIN on the update and neither worked. Only setting lock screen security to none works currently on my Pixel for twrp.

**Comment by StealUrKill** [comment]
We are all having the issues bggold. Here is a dmesg log from recovery will the issue is happening. This seems to be giving the issue.
`<14>[    2.910494] c1      1 init: processing action (crypto.ready=1) from (/init.recovery.taimen.rc:89)
<14>[    2.910562] c1      1 init: starting service 'hwservicemanager'...
<11>[    2.911102] c1      1 init: Failed to open /acct/uid_0/pid_613/cgroup.procs: No such file or directory
<11>[    2.911131] c1      1 init: createProcessGroup(0, 613) failed for service 'hwservicemanager': No such file or directory
<14>[    2.911300] c1      1 init: Service 'prepdecrypt' (pid 571) exited with status 0
<14>[    2.911350] c1      1 init: starting service 'keymaster-3-0'...
<11>[    2.911763] c1      1 init: Failed to open /acct/uid_0/pid_614/cgroup.procs: No such file or directory
<11>[    2.911788] c1      1 init: createProcessGroup(0, 614) failed for service 'keymaster-3-0': No such file or directory
<14>[    2.911874] c1      1 init: starting service 'gatekeeper-1-0'...
<11>[    2.912295] c1      1 init: Failed to open /acct/uid_0/pid_615/cgroup.procs: No such file or directory
<11>[    2.912326] c1      1 init: createProcessGroup(0, 615) failed for service 'gatekeeper-1-0': No such file or directory
<14>[    2.912441] c1      1 init: starting service 'sbinqseecomd'...
<11>[    2.912874] c1      1 init: Failed to open /acct/uid_0/pid_616/cgroup.procs: No such file or directory
<11>[    2.912902] c1      1 init: createProcessGroup(0, 616) failed for service 'sbinqseecomd': No such file or directory
<14>[    2.913029] c1      1 init: starting service 'ese_load'...
<11>[    2.913446] c1      1 init: Failed to open /acct/uid_0/pid_617/cgroup.procs: No such file or directory
<11>[    2.913477] c1      1 init: createProcessGroup(0, 617) failed for service 'ese_load': No such file or directory
<14>[    2.913594] c1      1 init: starting service 'esed'...
<11>[    2.914057] c1      1 init: Failed to open /acct/uid_0/pid_618/cgroup.procs: No such file or directory
<11>[    2.914091] c1      1 init: createProcessGroup(0, 618) failed for service 'esed': No such file or directory
<14>[    2.914218] c1      1 init: starting service 'servicemanager'...
<11>[    2.914644] c1      1 init: Failed to open /acct/uid_0/pid_619/cgroup.procs: No such file or directory
<11>[    2.914673] c1      1 init: createProcessGroup(0, 619) failed for service 'servicemanager': No such file or directory
<11>[    2.922088] c5    619 init: couldn't write 619 to /dev/cpuset/system-background/tasks: No such file or directory
<14>[    2.924541] c1      1 init: Service 'ese_load' (pid 617) exited with status 2
<11>[    2.928642] c1      1 selinux: avc:  denied  { set } for property=hwservicemanager.ready pid=613 uid=0 gid=0 scontext=u:r:recovery:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=property_service permissive=1`
[dmesg.log](https://github.com/TeamWin/Team-Win-Recovery-Project/files/1734549/dmesg.log)

**Comment by hackel** [comment]
Is this fixed by e131bec179826431b7b89e4748ae05e8a4262145?  Has anyone tried to compile it?

**Comment by RuioWolf** [comment]
Can you guys mount /cache ? Feels like it can't works as well…

**Comment by theqwertyipad** [comment]
Same situation on Nexus 5X with February patch...

**Comment by chetgurevitch** [comment]
Found the [relevant commit in aosp](https://android.googlesource.com/platform/frameworks/base/+/5025791ac6d1538224e19189397de8d71dcb1a12). Will see what I can do.

**Comment by kmahyyg** [comment]
Temporarily you need to remove your screen protection such as PIN,Pattern,Password to get TWRP worked.

Waiting for next version to solve this major problem.  
[MARK]


Device: sailfish (Pixel 1st gen, with AOSP latest package)

**Comment by timkgh** [comment]
Is the P2XL 3.2.1-2 a confirmed fix that might also work on the 5X?
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/854#issuecomment-367531054

**Comment by chetgurevitch** [comment]
@timkgh Yes the fix for all devices has been upstreamed, @bggold this issue has been fixed as of 3.2.1-2 and should be closed.

**Comment by neekless** [comment]
@chetgurevitch 3.2.1-2 has been released for all pixel devices a few days ago but they're not available for bullhead and angler. Will they be getting 3.2.1-2 as well?

edit: nvm, the 3.2.1-0 for bullhead and angler linked in [#854 (comment)](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/854#issuecomment-372503905) is updated and fixed.
