### ISSUE TITLE
Xiaomi MI A1: none of the available images work in `fastboot boot` mode

### ISSUE THREAD

**Issue by birdie-github** [TeamWin/Team-Win-Recovery-Project#1203]
```
$ fastboot boot twrp-3.2.1-0-tissot.img

astboot boot twrp-3.2.1-0-tissot.img 
downloading 'boot.img'...
OKAY [  1.244s]
booting...
OKAY [  0.622s]
finished. total time: 1.866s
```

Reboots into the system. Likewise with version 3.1.1 ( twrp-3.1.1-0-tissot.img ).

A custom build, recovery-3.2.1-2-oreo.img works.

My phone runs the latest stable release from Febrary 2018.

**Comment by 3yan** [comment]
same here,
recovery from https://forum.xda-developers.com/mi-a1/development/recovery-twrp-3-1-1-0-touch-recovery-t3688472 has worked flawlessly by fastboot boot. Source code here: https://github.com/mohancm/recovery_device_xiaomi_tissot .

my mi a1 is fresh from box with android 7.1.2

**Comment by tjanez** [comment]
I've dug a bit further into this.

The [official TWRP git repo for Xiaomi Mi A1](https://github.com/TeamWin/android_device_xiaomi_tissot) is a fork of @mohancm's [TWRP git repo for Xiaomi Mi A1](https://github.com/mohancm/recovery_device_xiaomi_tissot). However, [the first is 7 commits behind the @mohancm's `oreo` branch](https://github.com/TeamWin/android_device_xiaomi_tissot/compare/android-7.1...mohancm:oreo).

@mohancm, since you are listed as the maintainer on the [official TWRP page for Xiaomi Mi A1](https://twrp.me/xiaomi/xiaomimia1.html), can I ask you to update the official TWRP git repo for Xiaomi Mi A1 and rebuild the image?

**Comment by birdie-github** [comment]
I no longer have this device and TWRP is now at version 3.3.1, so I'm closing this issue.
