### ISSUE TITLE
Wiping Ext4

### ISSUE THREAD

**Issue by ulmo20** [TeamWin/Team-Win-Recovery-Project#121]
I recently updated to TWRP 2.4.3.0.  After installing a rom with EXT4 file systems, I was unable to wipe data, system, cache, or dalvik partitions.  Also, any roms that attempted to wipe any directories would fail.  The original rom with the EXT4 filesystems would reinstall normally.  

I eventually downgraded to TWRP 2.2.0 and was able to wipe the directories normally.

Log from TWRP  https://dl.dropbox.com/u/23638797/recovery.log

**Comment by Dees-Troy** [comment]
Boot TWRP 2.4.3.0. Use the file manager under advanced to browse to /sbin and find and delete the make_ext4fs file. Now try wiping.

**Comment by gtdtm** [comment]
I had the same issue on my Droid Incredible 2. I'm not sure what the file system for the rom was, but the factory wipe, cache, and system wipes all failed, but then it wouldn't let me reboot saying there was no OS. I tried restoring, which then also failed. Unfortunately I was having ADB issues and couldn't roll back to a previous version, so I had to flash a new rom and switch to another recovery temporarily, so I can't try your fix at the moment. I've used every version of TWRP since probably 2.1 and have never had an issue before this.

**Comment by gtdtm** [comment]
In the interest of contributing back to you awesome devs...I went back to twrp to test your suggestion Dees. I deleted that file, which then did allow me to wipe successfully. One issue is that after I rebooted system and booted back into recover that file had reappeared. Hope that helps.

**Comment by ulmo20** [comment]
I also noticed the same problem with rebooting as well.  If I tried to reboot after having the problem with flashing, TWRP would give me a warning saying there was no Rom installed.  I also have used several different versions of TWRP and have never had this issue before.

Dees, I fixed the problem by switching to an older version of TWRP so I wasn't able to test your suggestion.

**Comment by Dees-Troy** [comment]
The latest build for Inc2 should be using mke2fs instead of make_ext4fs which should fix the wiping problems. Please let me know if you're still having issues with TWRP 2.4.4.0 or higher.
