### ISSUE TITLE
twrp-3.2.1-2-ocn incompatible with Oreo-based firmware

### ISSUE THREAD

**Issue by jackfang888** [TeamWin/Team-Win-Recovery-Project#1259]
I can no longer boot into TWRP on the HTC U11.

Previously I was on firmware ver 1.28.709.33 and the following commands worked perfectly:

```
adb reboot bootloader
fastboot boot twrp-3.2.1-2-ocn.img
```

I recently flashed an Oreo-based RUU (firmware 2.33.401.10), and now when attempting to run the above commands the phone is either hanging, or it only shows a black screen (it is difficult to tell which).  Holding VOLUP+VOLDWN+PWR to force a reboot is the only way out.

FWIW the command does still appear to complete successfully from the fastboot side of things:

```
C:\Phones\platform-tools>fastboot boot twrp-3.2.1-2-ocn.img
downloading 'boot.img'...
OKAY [  1.015s]
booting...
OKAY [ 10.099s]
finished. total time: 11.117s
```

**Comment by CaptainThrowback** [comment]
This is a known issue, which has been discussed in the XDA thread. On some devices, after updating to Oreo, you have to flash the recovery, rather than booting it. I have no explanation as to why this is the case. Fastboot boot still works fine for me.

EDIT: See this post - https://forum.xda-developers.com/u11/development/recovery-twrp-touch-recovery-t3617028/post76600970

EDIT 2: Either way, this issue isn't titled correctly. TWRP is compatible with Oreo-based firmware. Just fastboot boot isn't compatible with all devices running Oreo firmware.

**Comment by jackfang888** [comment]
If the issue is with fastboot, is it something I have to hope Google fixes?

**Comment by CaptainThrowback** [comment]
There's nothing for Google to fix. It works on some and not others. Possibly bootloader or dtb related. Nothing for anyone to do. You'll just have to flash it. Several previous HTC devices didn't have fastboot boot working at all, so just be happy it ever worked :/.

**Comment by jackfang888** [comment]
Ok thank you for the information!
