### ISSUE TITLE
Creating first backup on Nexus 4 fails due to wrong folder permissions

### ISSUE THREAD

**Issue by ogr3** [TeamWin/Team-Win-Recovery-Project#126]
Nexus 4 (mako) on 2.4.3.0 (factory reset phone)

When creating the first backup TWRP said that everything went great, but the folder /sdcard/TWRP was empty.

The folder was owned by root:root instead of sdcard_rw:sdcard_rw, so I guess it couldn't create the sub-folder structure.

I did chown sdcard_rw:sdcard_rw /sdcard/TWRP

and did a new backup. This time it went well.

Hopefully this can be fixed in a later release.

**Comment by bigbiff** [comment]
Does this still happen on 2.4.4.0?

**Comment by ogr3** [comment]
Yes 

/sdcard:

drwxrwxrwx    2 root     root          4096 Mar 16 15:29 TWRP
drwxrwxr-x    2 media_rw media_rw     73728 Mar 16 10:04 TitaniumBackup

/data/media:

drwxrwxrwx    3 root     root          4096 Mar  6 08:25 TWRP
drwxrwxr-x    2 media_rw media_rw      4096 Jan 24  1970 legacy

**Comment by ogr3** [comment]
You're writing to the physical path /data/media, where all files should be owned by media_rw:media_rw

I guess the symlinking to /sdcard gets fubar when the permissions are wrong.

Log:
http://pastebin.com/dg1Cx0s6

**Comment by ogr3** [comment]
FYI clockworkmod had exactly the same permissions bug then 6.0 came out. See the comments in this post:

https://plus.google.com/103583939320326217147/posts/L5aVZe7C9vg

I don't know how he fixed it though.

**Comment by Dees-Troy** [comment]
I looked at the way that CWM "fixed it" and they just chmod 777 everything so that everyone can do anything on the files and folders as seen here:
https://github.com/CyanogenMod/android_bootable_recovery/commit/382525c2ba8cb91933644cdf1f6703fa279388dd#L2R368

The backup folders for TWRP are created using this function:
https://github.com/TeamWin/Team-Win-Recovery-Project/blob/twrp2.4/twrp-functions.cpp#L147
and that function creates all folders with 777 permissions as well.
Since TWRP runs as root it really doesn't matter that the folders are owned by root because TWRP is root. If you're running on a freshly formatted /data then you may not be seeing your backups because the backups may actually be in /data/media/0/TWRP instead of /data/media/TWRP which may be why you're not seeing your backup after it's created. You're probably looking in the wrong folder.

I generally suggest that you ignore /sdcard as it's just a remount of a folder in /data. I only do that remount because people are derps and freak out when "/sdcard" doesn't exist in recovery because they don't understand how /data/media devices really work. The only reason I create "/sdcard" is to avoid the support headache that those people cause.

I generally consider this issue to be a non-issue. Below the surface, user and group names like root, system, and media_rw are mapped to numbers (e.g. root is almost always 0). On some devices the media_rw account is a different number. The recovery space can't always get to the correct uid and gid and the numbered account for the media folder varies. E.g. on some Sony stock ROMs they use 2800 for media_rw instead of 1023, so we can't safely chown the folder and be sure that we'll get the correct user and group account for all ROMs/devices.

**Comment by ogr3** [comment]
Fair enough. I can adb pull the files from /data/media when TWRP is booted since I'm root then.

However, TWRP also creates TWRP folder with a small file, .twrps under /data/media/0/. I suggest you only create files in one place so that you know where to restore them after i.e. a factory reset. Will it be sufficient to restore only /data/media/TWRP in order to restore from a backup?
