### ISSUE TITLE
Adding Samsung Galaxy S2 i9100G

### ISSUE THREAD

**Issue by rskyline** [TeamWin/Team-Win-Recovery-Project#13]
I didn't know how to post this, but i'm coming from Motorola Atrix and i really miss your recovery and i want to know if you can support the Samsung Galaxy S2 GT-I9100G version!

**Comment by Dees-Troy** [comment]
The problem with many Samsung phones is that Samsung decided to place the recovery in the boot partition instead of a separate recovery partition.  This arrangement means that anytime you install a new ROM or kernel, you will be stuck with whatever recovery the developer decided to include with their kernel.  I'm not sure that I could easily obtain an i9100G in the USA.  Most of the SGS2 phones in the USA where I live use the Qualcomm chipset and have a proper recovery partition due to Exynos chipsets not working with LTE radios.

I can say that TWRP does work on the SGS2 devices though and it's not that hard to get it working.  I know of a couple of developers that have it working and I have it working on the Samsung Epic 4G Touch which is a CDMA version of the i9100.  Someone donated an Epic Touch to me, so I can develop for and test on it.

So, your best bet would be to talk to a ROM or kernel developer for your device and ask them to consider making builds with TWRP.
