### ISSUE TITLE
[enhancement] Triple storage?

### ISSUE THREAD

**Issue by Rara-Avis** [TeamWin/Team-Win-Recovery-Project#130]
Hi!

What about adding third target for lucky owners of tablets having native internal /sdcard, external SD card as /external_sd and USB-OTG capable?

Something like
TW_OTG_STORAGE_PATH :=
TW_OTG_STORAGE_MOUNT_POINT :=

and appropriate option  where needed or external storage selection in settings?

**Comment by Dees-Troy** [comment]
My plan, since rewriting the entire partition management scheme in TWRP with 2.3, is to make the entire system capable of handling an essentially infinite number of storage locations. The goal is to create new GUI element(s) for backup, restore, mounting, wiping, and storage selection to make the handling of partitions more dynamic. I'm hoping to get to that point with TWRP 2.5, whenever that is. Basically I just need to catch the GUI up to what the back-end is capable of handling now.

**Comment by Dees-Troy** [comment]
This capability will be in 2.5 when it is released.
