### ISSUE TITLE
Decryption problem

### ISSUE THREAD

**Issue by appdevsw** [TeamWin/Team-Win-Recovery-Project#1352]
- [yes ] I am running an official build of TWRP, downloaded from https://twrp.me/Devices/
- [ yes] I am running the latest version of TWRP
- [ yes] I have read the FAQ (https://twrp.me/FAQ/)
- [ yes] I have searched for my issue and it does not already exist

I use Xiaomi mido and twrp-3.2.3-1-mido.img

Dear Team,
There is a lot of problems related to encryption and decryption.
Even now I found 10 issues on the first page of the issues list.
Often the problem is located in TWRP decryption, when the phone is encrypted using PIN
and TWRP displays a pattern as a method of encryption, 
and when the phone uses pattern, TWRP is asking for PIN.
But in these case it’s possible to decrypt the phone using shell command 
**twrp decrypt** _password_
and as a password you can use PIN or digit equivalents from the pattern.
I suppose that the method recognition is not clearly explained by phone producers or maybe the algorithm is often changed.
Maybe could you consider to allow users choose the method of decryption manually,
by adding buttons to the decryption screen?
**[password] [PIN] [3x3] [4x4] [5x5] [6x6]**

**Comment by CaptainThrowback** [comment]
That would just be a workaround. The detection should be fixed.

**Comment by storm49152** [comment]
Can I ask: why isn't a workaround good enough for "in the mean time"? Because judging by the number of reports about failing decryption it doesn't feel like much is done about it. I expect (hope) that is not the case, and I understand it's a free product so we can't really demand anything, but at least the workaround would be nice.. We now have to resort to using 3.2.1-1 or use the version from Codeworx to have a working TWRP.

**Comment by CaptainThrowback** [comment]
Someone would need to submit a code change for a workaround. So, rather than modifying the code to apply a workaround, why wouldn't a fix instead be made that makes the workaround unnecessary?

At the end of the day, the problem is that someone needs to step up and submit a fix to Gerrit for this issue. Until that happens, it will remain an issue.

Decryption support in TWRP never used to be the rule - it was the exception, mostly because device maintainers stepped up and added the necessary blobs to their devices for TWRP to properly support it. Without those device maintainers, and with the updates to encryption routines in newer Android versions, there's just no way for the **2** main TWRP devs, that don't even possess most of the supported devices, to support decryption on all devices. So if you really want this fixed, you need to find a dev to help push some code updates to Gerrit, or at the very least a device maintainer to fix it for the official TWRP.

If @codeworkx has a working TWRP, you should ask him to push the fix to the official TWRP Gerrit so that the official can also be updated. Or if it's just a build tree issue or something similar, he can contact @bigbiff or @Dees-Troy via e-mail to let them know what parameters to change.

**Comment by CaptainThrowback** [comment]
Also: https://twrp.me/faq/encryptionsupport.html

**Comment by aksh1618** [comment]
FWIW, using numpad equivalent of the pattern works, at least on mido with v3.2.3-1, with the mapping:
```  
  1  2  3
  4  5  6
  7  8  9
```

**Comment by CaptainThrowback** [comment]
@aksh1618 

That method is described here: https://twrp.me/faq/openrecoveryscript.html

under "Specific pattern decrypt note" as well.

**Comment by appdevsw** [comment]
I tried to analyze the issue.
In cryptfs.h password type are defined like:
#define CRYPT_TYPE_PASSWORD 0 /* master_key is encrypted with a password
                               * Must be zero to be compatible with pre-L
                               * devices where type is always password.*/
#define CRYPT_TYPE_DEFAULT  1 /* master_key is encrypted with default
                               * password */
#define CRYPT_TYPE_PATTERN  2 /* master_key is encrypted with a pattern */
#define CRYPT_TYPE_PIN      3 /* master_key is encrypted with a pin */


I flash AEX 8 and set the password, then pin and then pattern.
Each time I get the cryptofooter and checked if the type o password is OK:

Pattern – pasword type (crypt tp) = 2 :
magic____ majo mino ftrsize__ flags____
b1c4 d0b5 0001 0003 0930 0000 1000 0000
key_size_ crypt_tp_ fs_size____________
0010 0000 **0002 0000** bbaf 06a3 0000 0000

Pin: 3
Password: 0

Then I installed AEX 9 and done the same steps:

Pattern 3:
b1c4 d0b5 0001 0003 0930 0000 1000 0000
0010 0000 **0003 0000** bbaf 06a3 0000 0000
Pin 2:
b1c4 d0b5 0001 0003 0930 0000 1000 0000
0010 0000 **0002 0000** bbaf 06a3 0000 0000
Password 0:
b1c4 d0b5 0001 0003 0930 0000 1000 0000
0010 0000 **0000 0000** bbaf 06a3 0000 0000

As you see, in Android 9, pin and pattern types are different then these in Android 8.
It can be a bug, or maybe there were changes in this area.
I think and hope, the problem will be resolved after the stable version of Pie will be released.
So, I close the thread.

**Comment by CaptainThrowback** [comment]
@Dees-Troy 

Perhaps this will be helpful for updating?
