### ISSUE TITLE
Boot Scripting Bug

### ISSUE THREAD

**Issue by shumashv1** [TeamWin/Team-Win-Recovery-Project#15]
I'm running TWRP 2.2 on the HP Touchpad.  If you hit the boot script icon at the top left without a script being available, TWRP runs the non-existent script and then locks up.  Some keys work, like the back arrow, but any of the main gui items don't respond.  Only way to exit is long keypress on power button or hard reset.

**Comment by Dees-Troy** [comment]
I think that the button that you are referring to is what we call the "console" key.  This button opens the console output so that you can see some of the logging and output  from TWRP.  If you press the same button again the console will go away and let you resume normal use.  If this advice does not resolve your issue, let me know.

**Comment by shumashv1** [comment]
That did it. Thanks. 

----- Original Message -----
