### ISSUE TITLE
TWRP 2.5.0.0 Galaxy S4

### ISSUE THREAD

**Issue by crawrj** [TeamWin/Team-Win-Recovery-Project#166]
Touch sensitivity is very high. Can't mount usb to computer.

**Comment by cordell** [comment]
Touch sensitivity is really high, this is on both jfltespr and jfltecan. Im sure all s4 are having this.

**Comment by kmbear** [comment]
Can confirm touch sensitivity issue on Tmo version.  As well as unable to mount usb (and I can't remember from previous phones, but wasn't there a way to use adb while in recovery somewhere?)

UPDATE:
Correction on mounting usb.  Driver was missing.  Installed an ADB driver (because I wanted to use adb in recovery mode) but would imagine installing the correct mass storage driver would enable expected USB mount behavior.

**Comment by Migs3** [comment]
The touch screen is fixed, but some debugging was left on in 2.5.0.1.

Terminal Command is spammed with "E: TOUCH" messages when using the touch screen.

**Comment by cordell** [comment]
figured debugging was left on for a reason, so heres the log, thanks for correcting the touchiness so quick

https://dl.dropboxusercontent.com/u/25841607/last_log.txt

**Comment by Dees-Troy** [comment]
Fully fixed and the debugging is removed as of 2.5.0.2 builds for SGS4 devices.
