### ISSUE TITLE
2.6.1.0 Broken radio/baseband after flashing. (Nexus 4)

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#206]
Happens on a fresh install with some roms. No data, but WiFi and bluetooth seem to work. Baseband version listed as "unknown" in settings but bootloader shows correct baseband. I was able to get data back by changing the rom's updater-script and binary and re-flashing it. See details below.
last_log: http://pastebin.com/fMtiQFzL
The affected rom I used: https://drive.google.com/uc?id=0B3sMcQzGJpf2ODFhd1I0d3VLTlU&export=download

Speculation:
Many roms have an updater-script that uses "/dev/block/platform/msm_sdcc.1/by-name/boot" as the extraction path for the boot.img. Maybe 2.6.1.0 has an issue when using that path? I changed it to "/dev/block/mmcblk0p6" and data works. I had to use a different update-binary and consequently had to change the system format and mount path because the old system path did not work with the new update-binary.

**Comment by cb474** [comment]
I had this problem upgrading from PA 3.69 (Android 4.2) to PA 3.99 (Android 4.3).

I upgraded to 2.6.1.0 through GooManager first, then flashed the new bootloader and radio for 4.3 (from zips), then did a factory reset, then flashed the rom and gapps. Afterwords I had no network connection, but wifi worked, and in "about phone" it said "baseband unknown" and "imei unknown." Although if I booted into the bootloader, it correctly recognized the bootloader and baseband versions. I tried this process several times, always with the same results (and I had carefully checked the md5sums on my downloads).

I tried reflashing the bootloader and radio through fastboot, but that didn't help.

Then I downgraded to 2.6.0.0 (through fastboot), did the whole process over again (except flashing the bootloader and radio through fastboot) and everything was fine.

Quite a few people are reporting this problem in the Nexus 4 TWRP thread at XDA and in the PA thread. Some people seem to think it's the step of wiping data that causes the problem. I couldn't tell. And it seems the problem is not exclusive to PA, though some 4.3 roms work okay. 

http://forum.xda-developers.com/showthread.php?t=2002326
http://forum.xda-developers.com/showthread.php?t=2020336
