### ISSUE TITLE
HTC ONE SPRINT 2.6.3 Issues

### ISSUE THREAD

**Issue by Kraizk** [TeamWin/Team-Win-Recovery-Project#222]
1) When screen "sleeps" the device becomes unresponsive. back and home buttons vibrate but screen fails to wake
2) When in TWRP and a charger is connected after launching the charging percentage never updates to indicate it is plugged in (+ sign is never shown). If device is launched to recovery while plugged in + sign shows but percentage never updates.
3) USB OTG storage is not read

Latest sprint 4.3 update, rooted but remainder is stock.

**Comment by ghost** [comment]
Having all of the same issues here.  Most annoying by far is #1 because then you have to hold power and volume down to reboot the device.

Edit:  If you hit the power button, if you swipe to unlock in the spot where that graphic normally appears (even though screen is off) the screen will come back on.  One way around the issue till its fixed without having to force reboot.

**Comment by Kraizk** [comment]
Issue 2 is most concerning to me as there is no longer a confirmation off mode charging is working which (if broken) means the device may be bricked if the battery dies.

**Comment by kd1974** [comment]
Having all of the same issues.

**Comment by Dees-Troy** [comment]
You can go into settings->screen and disable the screen timeout. I don't have a Sprint HTC One so I can't fix the charging issue myself.
