### ISSUE TITLE
Unable to charge / float while switched off with TWRP

### ISSUE THREAD

**Issue by readmanr** [TeamWin/Team-Win-Recovery-Project#226]
Hello,

I have a confirmed issue with Team Win Recovery Project 2.6.3.0 for the HTC Desire S (saga), and also with 2.6.3.0 for the HTC Sensation XL (runnymede).
Other users also have this issue when I raised it on XDA Developers.

As soon as you connect a USB cable (PC or Charger) with CWM or TWRP the phone boots into recovery.
With 4EXT (both Touch and Classic) this doesn't happen, and works perfectly.
I know I don't have to power off to charge, and most of the time I don't, however there are times when I do.

It doesn't matter if the phone is fully charged, or partially, as soon as you connect power, the phone will boot into recovery.

If the phone is connected to power, and in recovery and you select Power Off from within TWRP, the boot simply reboots back into TWRP.

On devices with no alternate recovery, you have to use TWRP and then flash the stock recovery to stop the issue happening.

If others could test, and confirm for other devices that would be great.
CWM also has this issue, but 4EXT does not, so perhaps code can be examined to determine the cause. 
Obviously with a stock recovery, the issue is not present.

**Comment by Dees-Troy** [comment]
saga is an old device that we've been building in CM7. We're dropping all devices that we've been building in gingerbread and ICS trees due to the lack of SELinux support in those trees, which means that we'll be dropping the saga from our officially supported device list. If a developer wants to come along and re-port TWRP to saga then we'll look at re-adding it, but the device is too old at this point for us to spend the time updating it ourselves. Sorry.
