### ISSUE TITLE
Cannot decrypt data partition

### ISSUE THREAD

**Issue by Nirudha** [TeamWin/Team-Win-Recovery-Project#247]
I'm on a Nexus 5 running the 4.4.2 derived Cataclysm ROM. I have Android encryption enabled and in the past have had no issues accessing the data partition from TWRP. However I used the following tool to change the decrypt password and unlink it from the screen unlock PIN.

https://play.google.com/store/apps/details?id=org.nick.cryptfs.passwdmanager

Now TWRP cannot decrypt the partition though Android itself has no issue and boots fine using it. Last log file is at https://drive.google.com/file/d/0B_-eQ07F2l3iVnZiOWpnaTRBdUU/edit?usp=sharing

The error just states that the password is incorrect.

**Comment by kogir** [comment]
I'm using an HTC One Developer Edition converted to the Google Phone Edition. It's on 4.4.2.

I used the same utility to change the password on 4.4, and it worked fine in TWRP. On 4.4.2, nothing works, even when the passwords are in sync (reset by changing the PIN). I'm guessing something changed between 4.4 and 4.4.2 with respect to encryption, key derivation, or however you check for success.

Please let me know if there's any other information I can provide that might help.

**Comment by kogir** [comment]
Actually, `ro.crypto.scrypt_params=16:3:1` in build.prop leads me to believe they switched from PBKDF2 to scrypt.

**Comment by kogir** [comment]
Oh, neat, the details are here: https://android.googlesource.com/platform/system/vold/+/android-4.4.2_r1/cryptfs.c

I'll try my hand at submitting a patch.

**Comment by Nirudha** [comment]
Hi Nick,

I just double checked now by resetting the pin and twrp does decrypt the
partition once I do. I'll check my build prop settings.

Thanks.

**Comment by gumbi2400** [comment]
I am having this issue as well. I did attempt to change the pin with no effect. I'm suspect its due to the switch to script on 4.4.2. I'm using TWRP 2.6.3.1 (the latest available for my d2vzw). The relevant log is:

Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:Unable to mount '/external_sd'
I:Actual block device: '', current file system: 'vfat'
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:Unable to mount '/external_sd'

If I'm missing something please let me know.

**Comment by Nirudha** [comment]
I reset the crypt fs password to a new one which is NOT the pin code and
TWRP was able to decrypt it. So perhaps it was the password itself. Maybe
some of the characters were not being entered properly with the TWRP
keyboard.

**Comment by gumbi2400** [comment]
Tried resetting password separately and together. Still no luck. I guess I'll be wiping my data partition. Sad day...

**Comment by ldanicel** [comment]
Any updates here ? I have 4.4.2 and experience the same issue... if you need logs or testing I can provide since I'm stuck with my phone encrypted and not being able to flash/update my firmware :)

**Comment by gumbi2400** [comment]
Unfortunately, no update for me. I eventually had to wipe everything and start over again. It was not fun. If you do go that route. Make sure you have a full backup from something like Titanium Backup.

**Comment by ldanicel** [comment]
I'd prefer seeing this fixed. I just finished setting this up from a fresh install and will definitely not go through it again :)
Are there no devs around ?

**Comment by cyber25** [comment]
Few days ago updated my HTC One to 4.4.2 rom (Elegancia) and got the same problem... Resetting password don't help. Tried TWRP v2.6.3.3 & 2.6.3.4. As result - cannot install OTA update :(

**Comment by edoardocomar** [comment]
Same issue here.
Galaxy Note 2, custom 4.4.2 ROM is Unofficial CyanogenMod11-Linaro
TWRP 2.6.3.1 - but have tried also 2.6.3.0, 2.6.1.0 ... 

init.svc.adbd=running

I:Copying file /cache/recovery/log to /cache/recovery/last_log
I:Is encrypted, do decrypt page first
I:Switching packages (TWRP)
I:Set page: 'decrypt'
I:Set page: 'trydecrypt'
I:cmd: /sbin/exfat-fuse -o big_writes,max_read=131072,max_write=131072 /dev/block/mmcblk1p1 /external_sdcard
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Set page: 'trydecrypt'
Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Cannot find file /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Set page: 'main'
I:Set page: 'clear_vars'
I:Set page: 'main2'
I:Cannot load settings -- encrypted.
I:Switching packages (TWRP)
I:Set page: 'reboot'
I:Set page: 'rebootcheck'
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
Starting TWRP 2.6.3.1 on Wed Feb 12 13:09:28 2014
BOARD_HAS_NO_REAL_SDCARD := true
I:Internal path defined: '/data/media'
I:External path defined: '/external_sdcard'
I:Mount: Unable to find partition for path '/data'
SP1_NAME := efs
SP2_NAME := modem
RECOVERY_SDCARD_ON_DATA := true
TW_NO_USB_STORAGE := true
TW_INCLUDE_CRYPTO := true
I:TW_BRIGHTNESS_PATH := /sys/devices/platform/s5p-dsim.0/s6evr02/backlight/panel/brightness
Starting the UI...Pixel format: 720x1280 @ 32bpp
Pixel format: BGR_565
framebuffer: fd 4 (720 x 1280)
=> Linking mtab
=> Processing recovery.fstab
I:Processing '/efs'
I:Processing '/boot'
I:Processing '/recovery'
I:Processing '/modem'
I:Processing '/cache'
I:Processing '/system'
I:Processing '/data'
I:Can't probe device /dev/block/mmcblk0p16
I:Unable to mount '/data'
I:Actual block device: '/dev/block/mmcblk0p16', current file system: 'ext4'
I:Can't probe device /dev/block/mmcblk0p16
I:Unable to mount '/data'
I:Actual block device: '/dev/block/mmcblk0p16', current file system: 'ext4'
I:Backup folder set to '/data/media/TWRP/BACKUPS/4df1e6ef53f58fe3'
I:Settings storage is '/data/media'
I:Processing '/external_sdcard'
I:Created '/external_sdcard' folder.
I:Processing '/usb-otg'
I:Created '/usb-otg' folder.
Updating partition details...
I:cmd: /sbin/exfat-fuse -o big_writes,max_read=131072,max_write=131072 /dev/block/mmcblk1p1 /external_sdcard
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
I:Unable to mount '/usb-otg'
I:Actual block device: '', current file system: 'vfat'
I:Unmounting main partitions...

....

/data | /dev/block/mmcblk0p16 | Size: 10880MB
   Flags: Can_Be_Wiped Can_Be_Backed_Up Wipe_During_Factory_Reset Wipe_Available_in_GUI IsPresent Can_Be_Encrypted Is_Encrypted Has_Data_Media Can_Encrypt_Backup Use_Userdata_Encryption Is_Storage Is_Settings_Storage 
   Symlink_Path: /data/media
   Symlink_Mount_Point: /sdcard
   Primary_Block_Device: /dev/block/mmcblk0p16
   Length: -32768
   Display_Name: data
   Storage_Name: Internal Storage
   Backup_Path: /data
   Backup_Name: data
   Backup_Display_Name: Data
   Storage_Path: /data/media
   Current_File_System: emmc
   Fstab_File_System: ext4
   Backup_Method: dd

**Comment by Dees-Troy** [comment]
4.4 Kit Kat introduced a few changes to the way that Google handles encryption / decryption so we had to update TWRP.  I just did fresh encryption on 4.4.2 stock AOSP ROM on my Nexus 7 2012 grouper and the latest TWRP decrypts it fine. Make sure you're on the latest TWRP for your device. Some devices may still need to be updated to support 4.4 decryption and hopefully we'll be rolling out updates soon.

Samsung devices present a special challenge for us. TouchWiz decryption code needs to be updated to support AOSP 4.4 decryption, so as of now, it's kind of one or the other. You can have TouchWiz decrypt OR AOSP 4.4 but not both. I'm not a big fan of Samsung in general and I currently only have one Samsung TouchWiz phone in my device stable. Ideally I would like to have 2 Samsung devices -- one encrypted with TouchWiz and the other with AOSP so that I can test and ensure that both forms of encryption are properly supported with the same code.

Last I checked the HTC One's Google Edition ROM was NOT using AOSP encryption. Instead it uses whatever HTC uses in their Sense ROMs. I've not got the time or proper resources to figure out what HTC's methods are so its encryption methods are not supported by TWRP.

I consider decryption support in recovery to be a "luxury item". Most users don't use encryption and it's very time consuming to develop for and support it especially across multiple devices and versions of Android. My main goal will be to support decryption on Nexus devices. Some other device makers' stock ROMs seem to stick to AOSP's encryption routines (Sony, Asus, LG maybe). Others don't (Samsung, HTC). We also don't own or have access to many of the devices we support making it impossible for us to test and ensure that decrypt works for each device. Our source code is public and others are welcome to download it and improve the decryption routines to support their devices and hopefully push their changes up to mainline TWRP.

**Comment by kogir** [comment]
As I mentioned in an earlier comment, Google changed both how they calculate the keys from the user's password and the format of the encryption header on disk:

https://android.googlesource.com/platform/system/vold/+/android-4.4.2_r1/cryptfs.c

Note commit c4c70f1 at https://android.googlesource.com/platform/system/vold/+log/android-4.4.2_r1/cryptfs.c

The latest TWRP for my device, 2.6.3.3, does not support scrypt key derivation.

I understand the changes, and would be happy to submit a patch that supports the new header format and key derivation, and doesn't auto-upgrade the on-disk header on non-4.4.2 devices.

The problem I ran into is that it's not clear which repo to fork, and which branch to patch. Should I ask for guidance on IRC? Should I try to merge only this change or all changes from 4.4.2?

**Comment by edoardocomar** [comment]
@Dees-Troy  
you said "I just did fresh encryption on 4.4.2 stock AOSP ROM on my Nexus 7 2012 grouper and the latest TWRP decrypts it fine. "

what is your latest TWRP ?

TWRP 2.6.3.1 - the latest for t03g (Galaxy Note 2) - does not decrypt an AOSP 4.4.2 ROM (CM-11) encryption.
I even tried 2.6.3.7 for t0lte - same error.

**Comment by edoardocomar** [comment]
@Dees-Troy  "I consider decryption support in recovery to be a "luxury item"."

well I think it is essential for those who run a custom recovery, isn't it? 
else anyone grabbing hold of the device can slurp all the user data by restarting the phone in recovery and connecting via adb . Googling a bit looks you can even get hold of the google account credentials http://kyleosborn.com/android/AndroidPhySec.pdf

**Comment by ldanicel** [comment]
@Dees-Troy - This feature is an essential _basic_ security feature for any mobile out there.
If you don't have what it takes to fix it then what costs you to guide @kogir through the patch submitting process so that we can all benefit off this feature ?
Closing issues doesn't make them go away.

**Comment by rmenessec** [comment]
Encryption is really a must-have for me. I wouldn't have installed OmniROM and TWRP2 if I had realized that I wouldn't be able to use encryption on 4.4.2. Please add this very necessary support.

**Comment by edoardocomar** [comment]
bigbiff made a build that I could test and worked :
http://forum.xda-developers.com/showpost.php?p=50278711&postcount=1181

**Comment by Xoib** [comment]
This issue should be re-opened ! Indeed in the Nexus 4 stock 4.4.2 and TWRP 2.6.3.3 the problem is still present.

**Comment by Dees-Troy** [comment]
I merged the fixes for 4.4 decrypt a while back (see link below). When we finish with TWRP 2.7 and do another full roll out most devices should be fixed. If you need it sooner, feel free to compile your own from the sources available in Omni.
https://gerrit.omnirom.org/#/c/1638/

While decryption support in recovery may be critical for those that want to run custom ROMs, I still firmly believe that most users do not encrypt their devices. I don't. TWRP is free open source software. We don't charge for this software and we don't get paid for the work that we do on it, so be careful what you request and be careful about how demanding your are when you request it. We do what we can but this is just a hobby for us, not a full-time job.

**Comment by ldanicel** [comment]
My problem was solely with the fact that you closed the issue.
Anyway, thanks ;)

**Comment by Xoib** [comment]
It was the same thought than @ldanicel. Thanks @Dees-Troy !

**Comment by edoardocomar** [comment]
In 2.6.3.2 just released for the t03g (n7100, galaxy note 2) the decryption works :-)

**Comment by ldanicel** [comment]
I confirm that. issue got fixed in 2.6.3.2.
Thanks @Dees-Troy !

**Comment by Xoib** [comment]
Ok. I hope mako will not be forgot during the next build run. By the way for mako it will be 2.6.3.4.

**Comment by gumbi2400** [comment]
Just updated to TWRP 2.7.0.0 on my d2vzw (verizon galaxy s3). Encrypted again, and attempted to decrypt. Same error in the logs:

Warning: crypto footer minor version 2, expected 0, continuing...
Error temp mounting decrypted block device
E:Failed to decrypt data.
I:Set page: 'decrypt'

Am I missing something obvious here?

**Comment by h-2** [comment]
I have just updated to TWRP 2.7.0, I still cannot decrypt my data partition. The device is a Asus TF700t.

**Comment by renegart** [comment]
Same here on a Galaxy Nexus. It's not possible to decrypt the device with TWRP 2.7.0.0

**Comment by ldanicel** [comment]
Well, unless you need 2.7.0 you could search and grab a 2.6.3.2  build which works fine.
Although yeah, I do not understand why would they revert the fix in trunk ... I'm too afraid to update : - )

**Comment by leo-bogert** [comment]
- I still get "Warning: crypto footer minor version 2, expected 0, continuing..." with TWRP 2.7.0.0. on Galaxy Nexus encrypted with CyanogenMod build cm-11-20140405-SNAPSHOT-M5-maguro.zip 
- Someone claims to know the reason there, so you might be able to fix it: https://github.com/TeamWin/Team-Win-Recovery-Project/issues/263

**Comment by leo-bogert** [comment]
@ldanicel 2.6.3.2 works indeed for me! Thank you very much.

**Comment by vsht** [comment]
I confirm that TWRP 2.6.3.2 can decrypt the data partition on Galaxy Nexus, while TWRP 2.7.0.0 cannot. Downgraded from 2.7.0.0 to 2.6.3.2 and everything is working fine now.

**Comment by eboth225** [comment]
I'm trying to downgrade to 2.6.3.2 on my verizon galaxy s3 but cannot find the version on the website:
http://techerrata.com/browse/twrp2/d2vzw

Any advice on how I can install this so I can get past this annoying issue?  Thanks.

**Comment by pingerer** [comment]
I am facing the same issue with att galaxy s3 and twrp 2.7.0.0. I encrypted the device with the latest d2lte cm11 nightly and had to factory reset back to cm10.1.3 because this is the last build that twrp can decrypt. There is also no twrp 2.6.3.2 for this device and 2.6.3.1 cannot decrypt either.

Any help will be appreciated.

**Comment by REDLINK** [comment]
I can also confirm that it's broken again in 2.7.0.0.

**Comment by edoardocomar** [comment]
on my Galaxy Note 2 (n7100) running cm11,
twrp 2.7.0.0 can decrypt data
twrp 2.7.0.2 can not - does not even ask for the password

**Comment by SaltwaterC** [comment]
Despite the changelog for 2.7.0.0, confirming the issue with cm-11-20140504-SNAPSHOT-M6-i9300.zip.

Also related to the encryption support, the adb sideload works but it breaks something in the process. With CM stock kernel it would simply crash roughly at the time it asks for the SIM PIN, while with the Boeffla kernel it freezes after the encryption password is accepted. I had to format the device, removing the encryption in the process, to see that the sideload flash went through.

**Comment by REDLINK** [comment]
Did somebody already have a chance to check if this is fixed with 2.7.1.0?

**Comment by ajfite** [comment]
I can't decrypt in 2.7.1.1 on Moto X

**Comment by butlerm1977** [comment]
I flashed the 2.7.1.0 twrp on Galaxy Nexus (toro) and it successfully decrypted 4.4.2.  I was using 2.7.0.0 with no luck.  i used Flashify to install the latest IMG.  Thanks!!!

**Comment by pauldmartinphd** [comment]
I can't decrypt with 2.7.1.0 on d2tmo.  Same error as everyone else.

**Comment by h-2** [comment]
Still not working with 2.7.1.1 on TF700T. This is really annoying :(

**Comment by boeleman** [comment]
Same problem with d2can on 2.7.1.0

**Comment by alextoombs** [comment]
+1, happening on d2vzw with 2.7.1.0

**Comment by nn2s2u** [comment]
I updated to 2.7.1.0 on a Galaxy Nexus, Verizon Toro, and it successfully decrypted 4.4.2. I was using 2.7.0.0, and was getting the failed to decrypt data errors.

**Comment by ccoager** [comment]
Is this issue isolated to encrypted devices only on 4.4.2 or newer?  I've tried multiple versions and none of them work.  I have seen reports on the XDA forums that there is a test build floating around that fixes this issue.  I'm looking for a fix for d2vzw if anyone has a test build.

**Comment by nn2s2u** [comment]
It worked for me with version android version 4.3 and 2.7.0.0 of twrp, IIRC.

**Comment by codemonkee** [comment]
Tried the following on SGS3 running CM11-20140708-SNAPSHOT-M8 (4.4.4)
TWRP v2.6.3.0 [d2can] - Unable to decrypt
TWRP v2.7.0.0 [d2can] - Unable to decrypt
TWRP v2.7.1.0 [d2can] - Unable to decrypt

**Comment by kasiub** [comment]
I have the same issue with cyanogen M8 on GT-I9300...

**Comment by REDLINK** [comment]
Since zips can be installed anyway and NANDroid backups can be made using Online Nandroid Backup this isn't the worst issue, but if it would be fixed that would be nice anyway. Unfortunately, I'm not competent enough in this area :(

**Comment by bill-mcgonigle** [comment]
Has anybody here identified the commit that fixed it in 2.6.3.2 and where it reverted in 2.7?  I'm in the same boat with no 2.6.3.2 for SGS4 (jflte).

**Comment by Dees-Troy** [comment]
I replied to this issue a LONG time ago trying to help clear some things up, by my reply was largely misunderstood or ignored. I'll try again today, since it's been a while.

On some devices, namely HTC and Samsung, the encryption methods used are different from AOSP. Someone helped us get TouchWiz decryption working a while back, but Samsung has since updated their encryption methods and TouchWiz decryption no longer works if you encrypt using TouchWiz in an Android version 4.3 or higher. The code that we use for TouchWiz decryption does NOT support AOSP decryption on 4.4 Kit Kat. Since TouchWiz decrypt no longer works on the latest versions of TouchWiz, I'm probably going to drop it from device configs in favor of supporting only AOSP including 4.4. Some of the decrypt problems that people are experiencing are due to our current inability to support TouchWiz decrypt and AOSP 4.4 at the same time.

HTC Sense encryption is NOT supported at all. It seems that even Google Edition HTC devices are using HTC's encryption and NOT AOSP's encryption. For HTC devices, you will have to use an AOSP based ROM that is NOT Google Edition.

Decryption support is not built into all builds of TWRP. Most times it's probably just an oversight. Sometimes it's because adding it makes the recovery image too big to fit in the device's recovery partition.

Android L decrypt is currently NOT supported. We will probably add support for this when L is finalized and all the source code is published.

Recovery only supports 96 characters. Some special characters may not be accessible in the password entry for decryption.

Generally speaking, decryption works with:
AOSP and AOSP based custom ROMs like Omni, PA, CM, Slim, Gummy, etc on any supported device
Asus stock ROM
Sony stock ROM

Choose your device and your software wisely.

**Comment by rmenessec** [comment]
In case it helps anyone, I'd like to mention that TWRP2 /data decryption is working fine for me. Encryption set up on OmniROM during 4.4.2; currently running 4.4.4. Samsung Galaxy Note 2 (t0ltevzw / i605).

There was a problem some months ago where AOSP decryption was _not_ supported by TWRP2, but it's since been fixed.

**Comment by bill-mcgonigle** [comment]
Thanks for clarifying @Dees-Troy! Your strategy sounds right - not just because it'll benefit my 4.4.4 (CM11) device, but also because AOSP encryption finally seems to have "gotten it right" and manufacturers will probably move to it as they can, now and especialy with L.  And the older images will still be there for people with stranded older devices.  I wrote up a workaround for users needing to do updates in the meantime:
https://www.bfccomputing.com/updating-cyanogenmod-11-kitkat-milestones-on-encrypted-devices/

**Comment by jcwenger** [comment]
Thank you very much for the info, @Dees-Troy.  

Is there an alternate option available?  

I understand that backup s of /data itself is obviously off the table.  How about installing a flashable zip?  

Can I use USB OTG?  Is there any specific gotcha with Dev L + N5 + USB OTG?

**Comment by boeleman** [comment]
One option would be to check whether CWM Recovery supports your device. Then you'll have access to MiniVold in recovery mode and you can mount encrypted partitions through adb.  I prefer the TWR method of just typing in my password, but as long as that does not work on my Galaxy S3, this does:

adb shell

setprop ro.crypto.state encrypted
vdc cryptfs checkpw 'your passphrase here'
mount /dev/block/dm-0 /data

and when you're done backing up/installing a zip

umount /data

**Comment by vsht** [comment]
The 2.7.1.0 version can indeed decrypt Galaxy Nexus which was previously encrypted by AOKP or Cyanogenmod. This was not possible with 2.7.0.0. Thanks for fixing :)

**Comment by konjiki7** [comment]
"Android L decrypt is currently NOT supported. We will probably add support for this when L is finalized and all the source code is published."

Running Pure-White Android L build right now and can't wait to get the support... For now finding a means of doing a backup image without recovery....fun

**Comment by altexdim** [comment]
(copy from #269)
I've found a way to mount encrypted partition on HTC ONE with the latest android version 4.4.3 
It's a python script, that can extract decrypted key from encrypted header and footer, so you can unterstand the algorythm.
I've got original python script from https://github.com/santoku/Santoku-Linux.git and hardcoded support for the HTC ONE (basicaly changed key size to 32, iv size to 32, aes_128_cbc to aes_256_cbc).
Here it is http://pastebin.com/TAeA6rSw
So, can i ask you @Dees-Troy to implement HTC ONE encryption into your TWRP project based on the algorythm in my script?

**Comment by bgcngm** [comment]
@Dees-Troy, any words on the above comment? Could we expect support for HTC's storage encryption?

**Comment by SuperBoy22** [comment]
@Dees-Troy Could you please comment on the above post? Thanks

**Comment by aTanCS** [comment]
LG G2 Stock ROM, TWRP 2.8.0.1, encrypted /data, can't mount. So I can't even wipe dalvik cache.

**Comment by generalmx** [comment]
First I'd like to thank @boeleman for his suggestion, as now I can actually decrypt my SGS3 on KitKat. I've posted a link to here with an explanation on all the SGS3 forums in xda-developers.

Starting in Android 5.0, device encryption will no longer be opt-in, instead opt-out. Perhaps instead of supporting myriad crypto libs you could try including minivold like CWM does, and provide an interface to scripts to use with it? As minivold works beautifully for me on CWM with my SGS3 encrypted by AOSP KitKat, but TWRP hasn't since pre-KitKat, and going back to pre-KitKat isn't an option anymore due to bootloader updates.

I'm going to go ahead and try the minivold binary from CWM while in TWRP, see if that works. Not sure if it needs explicit kernel support that's in TWRP's d2lte kernel already or not. But if it is a matter of just needing the binary, maybe at least some scripts could be provided to help us interact with it.

**Comment by h-2** [comment]
TWRP 2.8.3.0 now successfully decrypts my partition on every try [Asus TF700t]. Whatever it was, whoever fixed it: thanks a lot!

**Comment by bsilvertab** [comment]
Any updates on this issue for the M8?  Running Android L and unable to decrypt E: due to to OS encryption being enabled.

**Comment by Naddiseo** [comment]
@bsilvertab, works for me. Using M8 + cm-12 (Android L).

**Comment by bsilvertab** [comment]
What kind of lock screen are you using? I'm on a numeric pin and entering that 4 digit code in twrp gets rejected. I'm on the GPE rom for the m8.

**Comment by oneleft** [comment]
@bsilvertab, Sense ROMs and GPE ROMs use a variant of FDE which is not supported by twrp at the moment and likely wont be anytime soon.

**Comment by bsilvertab** [comment]
@oneleft What is fundamentally different about encryption between the different ROMs?  Is that not a function of Lollipop?

**Comment by BullHorn7** [comment]
Still having this. Nexua 5 version 5.1 with latest Twrp.

**Comment by bk-cribl** [comment]
htc one m8 dev edition leedroid on 5.1 with twrp 2.8.6 is failing for me right now.  tried 2.8.5, no luck as well.

**Comment by oneleft** [comment]
@bk10287 I wouldnt expect support for FDE in TWRP anytime soon.

**Comment by bk-cribl** [comment]
@oneleft why not?

**Comment by garvdd** [comment]
What should I do with the m8 I have all these apps and nothing works and it's making the phone run improper,should I factory reset it

**Comment by gerroon** [comment]
2.8.6.0 on Mondrian SM-t320 Android 4.4.4, password failed to decrypt data. I cant go into recovery ;(

**Comment by prisriya** [comment]
OK. I notice from the thread that there's a challenge with 4.4.2 and Samsung Touchwiz. However, I have an encrypted phone with that combi. I have rooted it, installed TWRP. Now TWRP backup is failing because of this error - unable to mount /data... Can you please recommend how to get past that problem.

**Comment by gerroon** [comment]
@prisriya

You have to disable "data" portion of the backup. TWRP cant decrypt the data portion because it is encrypted. So your backup will only contain the system files.

**Comment by prisriya** [comment]
Thx. I will give that a try. 
Q: If there's a problem when I flash a new ROM, I can only recover the system - but not the data that went along with it right?
OR
Q: If I have a backup using Titanium, can I restore the apps and the data, after restoring the system (in case there's an issue after flashing the new ROM).

Your response will be highly helpful

**Comment by Xoib** [comment]
@prisriya : The answers is yes for the two questions.

**Comment by prisriya** [comment]
Thx. @Xoib

**Comment by gerroon** [comment]
How about me? I answered you too ;)

**Comment by prisriya** [comment]
@gerroon my apologies for missing out earlier... thank you. All you folks have been instantly helping and responding... Thanks again!

**Comment by c3ph3us** [comment]
vdc cryptfs checkpw
CANNOT LINK EXECUTABLE: cannot locate symbol "__register_atf
page record for 0xb6f6002c was not found (block_size=32)

**Comment by SkullMasher** [comment]
`Failed to mount '/data' (Invalid argument)`

Trying to install Cyanogen Mod on a Nexus 4.
