### ISSUE TITLE
TWRP 2.6.3.4 on Nexus 5: ADB driver not installable @ Windows 8.1

### ISSUE THREAD

**Issue by marhry** [TeamWin/Team-Win-Recovery-Project#253]
I am using the newest image for the Nexus 5, TWRP 2.6.3.4, md5 verified, linked in the XDA rooting guide over here: http://forum.xda-developers.com/showthread.php?t=2507905
which points to http://techerrata.com/browse/twrp2/hammerhead

The standard USB driver for ADB I obtained through the Google Android SDK works fine for Fastboot or ADB once booted, but does not work in Recovery.
Instead, the following device shows up (excuse the German, should be understandable though):
![screenshot 2014-01-14 18 48 56](https://f.cloud.github.com/assets/5941638/1913112/3fcafef0-7d44-11e3-8c23-5639b17ae0fe.png)

Checking the android_winusb.inf file, I see that it does not contain an entry with the specific PID - fixing this is not easy as copying the lines inside the inf causes Windows to complain about an invalid .cat file.

Through some googling, I found that guy who has a similar problem: http://forums.androidcentral.com/google-nexus-5/343578-nexus-5-failing-show-up-adb-recovery.html
He could solve it through the use of some mysterious toolkit (which I will try now), but it seems a bit fishy to me to download some 80MB of toolkit just to fix a broken driver ID.

Is it possible instead of using a different VID/PID combo in recovery (and the custom name "AOSP on HammerHead"), to just use the same one that is used by the stock OS? My naive understanding is that this will cause the drivers to work.

Please ask if you need more information!

EDIT:

I managed to install the drivers through the mentioned toolkit: http://www.wugfresh.com/nrt/
By using the Wizard provided, I removed manually all old drivers associated with Google or Nexus devices and then reinstalled the universal driver.
Essentially, all you probably need to do is use these: https://github.com/koush/UniversalAdbDriver
Ironically, this one is made by koush of ClockworkMod fame (and has the side effect that my Nexus 5 now shows up as a Galaxy Nexus), so devs, please fix this bug!

Another problem with this method is that adb only works if you mount USB storage as PTP device. To fix this:
1. Mount as MTP
2. Go to the device manager 
3. Uninstall the ADB device that shows up. **Also tick "Remove drivers"**

Then you can reinstall the Google drivers and you should also have working ADB in MTP mode.

**Comment by marhry** [comment]
Something more I found: You are reusing the PID from the old Galaxy Nexus, at least according to the universal driver installer:
https://github.com/koush/UniversalAdbDriver/blob/master/usb_driver/android_winusb.inf#L82-91

I think changing the PID to 4EE2 so that the whole identifier is 
VID_18D1&PID_4EE2
could fix those driver problems.
Since it is not easy anymore for the "end user" to change the .inf file oneself in recent Windows versions without all that custom certificate signing "nonsense" and the WDK, I hope that's possible for you guys.

**Comment by chrone81** [comment]
Same here, using the USB driver v9 provided by Google from Android SDK still doesn't detect this. On Windows 8 the N5 is detected as AOSP on Hammerhead. I didn't try to install any Universal Naked Driver though, I'm afraid it might conflict with Google USB driver.

**Comment by Tasssadar** [comment]
This vid:pid is considered universal across all (at least nexus) devices, all of them have the same vid:pid when they are in recovery. See line 25 of [recovery's init.rc](https://android.googlesource.com/platform/bootable/recovery/+/android-4.4.2_r2/etc/init.rc) and this is the dmesg output of N5 running stock recovery connected to Linux PC:

```
[ 8449.670067] usb 2-1.1: new high-speed USB device number 11 using ehci-pci
[ 8449.755137] usb 2-1.1: New USB device found, idVendor=18d1, idProduct=d001
[ 8449.755149] usb 2-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 8449.755155] usb 2-1.1: Product: Nexus 5
[ 8449.755160] usb 2-1.1: Manufacturer: LGE
```

This is how it is supposed to be. If the Windows drivers are dumb, well, it's not TWRP's fault.

**Comment by marhry** [comment]
> This is how it is supposed to be. If the Windows drivers are dumb, well, it's not TWRP's fault.

So what you are saying is essentially "I don't care, Windows users are dumb, use Linux instead?". I don't see the downside of such a change. In Linux, you don't need to worry about the different PID, since you don't need to worry about the drivers.
In Windows, there is this whole mess of driver signing issues (which I do not like, but also cannot change), so it is not trivial to install a device with a non-matching PID.
The main point is that the "official" Google USB drivers contain no entry for 18D1:D001, check for yourself if you don't believe me: http://pastebin.com/CJwhhV8u
I understand the issue now and do not believe you are "at fault", but you could fix this whole situation, since I doubt that I can get Google to change the default USB driver.

**Comment by Dees-Troy** [comment]
The changes you're requesting would affect almost all devices. Instead you can submit a patch to the hammerhead repos in OmniROM to add an init.recovery.qcom.rc file that sets the correct USB IDs for this specific device if it's that important to you.

Bear in mind that this project is a hobby to most of us. We don't charge for the work we do and we don't get paid for it either. IMHO this isn't a case of Windows users are dumb or Linux is better. It's about contributing rather than complaining. If it's too much effort to contribute, don't complain. It's also a matter of what we have time for and what we feel like working on. Even simple changes have to be created, compiled, tested, pushed, reviewed, and merged. We're busy, and it's a thankless job.

**Comment by marhry** [comment]
Hey, please don't take this the wrong way! It seemed like a relatively small and "easy" fix from outside. I do develop software and could contribute, but I'm not familiar with TWRP or Android to be able to directly make a pull request. I'll look into it, though.
Also, since that's the issues section, you're more likely to encounter people like me who have a problem that they think "needs fixing". See it that way: I like your product that much, I'm willing to complain about it in a lenghty post ;)
Thank you very much for putting your time into this.

**Comment by BrentNewland** [comment]
Just wanted to add that it's pretty stupid you developers are refusing to fix this issue.

After installing TWRP and booting to it, Windows can't install the driver due to no drivers having matching HWID's. That means no ADB interfacing with TWRP, unless you use a workaround.

The solution is dead simple, it's right in the Android SDK driver:

;Google Nexus (generic)
%SingleBootLoaderInterface% = USB_Install, USB\VID_18D1&PID_4EE2

The Android SDK driver doesn't have entries for the Nexus 5, as you claim the d001 device ID is for.

So. All you have to do is change a tiny, minor, insignificant little entry, "d001", to "4ee2".

Your claim that "The changes you're requesting would affect almost all devices" is a load of crap. Unless by "affect almost all devices" you mean "would make TWRP actually work without going through needless bullshit".

As a workaround, you'll need to open Device Manager, find the android device that's missing a driver, right click and Update Driver, browse for a driver, "let me pick from a list", "all devices", "have disk", browse to the Android SDK Folder\extras\google\usb_driver, and choose "Android ADB Interface".

> This is how it is supposed to be. If the Windows drivers are dumb, well, it's not TWRP's fault.

If the developers insist on burying their heads in the sand (or, rather, up their own asses), then it is indeed their fault.

**Comment by ultrafez** [comment]
@BrentNewland: Just wanted to say thanks for your post (which I found by Googling for "aosp on hammerhead driver"), your workaround was by far the easiest way of getting the drivers to work without having to install extra software or do any other messing about.

**Comment by marhry** [comment]
@BrentNewland, @ultrafez: Just out of curiosity, which OS are you using?

With Windows 7, it should work as you described.

With Windows 8, as far as I know, you either have to reboot with 
(paraphrased) "Driver ID verification disabled", or manage to sign the 
driver yourself and recreate the .cat file if you touch the .inf.

**Comment by ultrafez** [comment]
I'm using Windows 7 64-bit and worked exactly as the workaround described. Haven't tried it with Windows 8.

**Comment by marhry** [comment]
> I'm using Windows 7 64-bit and worked exactly as the workaround
> described. Haven't tried it with Windows 8.

Alright, just asked to verify since you didn't include it in your post 
(the OP was about Win 8.1).
For anybody else arriving via Google, something like 
http://www.getdriver.com/how-to/2410/make-windows-7-drivers-work-windows-8-8-1-inf-modding.html#.U48aCCidREB 
should also work on Win8 in conjunction with the modified .inf file, 
though getting the UniversalAdbDriver is probably easier in that case.

**Comment by KOLANICH** [comment]
The same shit is for N7100
We need some of

```
USB\VID_04E8&PID_6860&REV_0400&ADB
USB\VID_04E8&PID_6860&ADB
```

to be written into script and sources (this was done in https://github.com/TeamWin/android_device_samsung_t03g/blob/cm10.1/init.rc#L52 but not used by unknown reason).
The better way is to have 2 files with vid and pid and use loaded values from them.

> Since it is not easy anymore for the "end user" to change the .inf file oneself in recent Windows versions without all that custom certificate signing "nonsense" and the WDK, I hope that's possible for you guys.

Really? The user only have to add a couple of lines into inf file and agree with red window. I have w8.1 and I have just made this procedure. No rebooting was needed. Maybe it is because I have x86 edition of windows.

**Comment by marhry** [comment]
> Really? The user only have to add a couple of lines into inf file and agree with red window. I have w8.1  and I have just made this procedure. No rebooting was needed. Maybe it is because I have x86 edition of windows.

Yep, see [this document](https://msdn.microsoft.com/en-us/library/windows/hardware/ff548231%28v=vs.85%29.aspx).

On x64, you need to do some not-so-obvious stuff to disable signature checking[1] which involves at least two reboots (to restore the original state afterwards). If you don't do this, you won't even get any windows where you can confirm that you know you're going to blow up your computer.

Not that I disagree with the idea of driver code signatures in principle! I just think the average user who wants to extend the life of his phone by rooting it should not have to deal with this added complexity. Given that the driver is already being signed, adding more/correct VIDs and PIDs is the way to go.

[1] that is, checking for its _presence_, not even if its signed by MS

**Comment by KOLANICH** [comment]
Thanks for the info.
