### ISSUE TITLE
TWRP producing incomplete backups

### ISSUE THREAD

**Issue by rmenessec** [TeamWin/Team-Win-Recovery-Project#268]
My backups have been failing silently since installing TWRP 2.7.0.0 (or before) on my t0ltevzw. Most of the simple application data (/data/data) was stored, but nearly all special directories created by applications were missed, as were all files in the root of the "SD" partition. (/storage/emulated/0)

I have made it a habit to save backups on both the external SD card and a USB flash drive (USB-OTG). Altogether, I had three backups total from three days, created about four days apart, with one copy each on external SD and USB flash drive. Every single one was missing data.

I didn't discover this until I encountered a problem that required me to restore from backup, so my /data and /system partitions have already been erased several times. I also reflashed the recovery partition with TWRP 2.6.3.0 to see if that would help. I cannot provide any kind of historical information to aid in debugging this problem.

I will be spending some hours tomorrow restoring everything I can from Titanium Backup and re-creating every single device preference from scratch, plus all the system applications that TWRP has NEVER backed up correctly, like XPrivacy and Greenify. (Will that ever be fixed?)

After that's complete, I can attempt to provide debugging information from creating new backups.

This might be a good time to add a "verify" step to TWRP backups which would compare the contents of the tarballs against the source data after a backup is complete. That would have caught the missing files.

**Comment by lefth** [comment]
Nothing in the /data/media folder is supposed to be backed up by TWRP. This is because a data wipe does not erase /data/media, and it is also easily backed up to computer without tools like TWRP. That being said, is there still data that's supposed to be backed up but is being missed? If so, it would be very helpful to describe what's being missed, and attach a log file (called /tmp/recovery.log, /cache/recovery/log, /cache/recovery/last_log, or /sdcard/recovery.log).
