### ISSUE TITLE
Date/Time are wrong in Samsung Galaxy S 5

### ISSUE THREAD

**Issue by Da-Av** [TeamWin/Team-Win-Recovery-Project#277]
In Samsung Galaxy S 5 (G900F) both date and time are wrong in TWRP 2.7.0.0.The timezone gives me an offset of 13 (my zone is +2, but the correct time is shown if I select zone -11). Date is also completely wrong.

**Comment by Tasssadar** [comment]
Try to turn on airplane mode in android and make sure you are not connected to any kind of network - no wifi, no mobile network no anything. Then restart the device. Does it have correct time and date after restart? Or is it wrong and changes to correct date only after you enable either wifi or mobile network?

If it is wrong after restart with no network connection in Android, then there is nothing TWRP can do - current time and date simply isn't stored anywhere on the device. If you're using some kind of custom ROM, it might be caused by time_daemon binary not working correctly, try to report it to the ROM's developer.

**Comment by qwerty22** [comment]
Galaxy S5 (G900F), TWRP 2.7.1.0
Before load TWRP I see corret time in system. 
In TWRP:
1. Inverted Time Zone. If i request "-4" I see "+4".
2. If local time 15:14 I see in TWRP 15:51
After restart I see corret time in system. 

Problem only in TWRP.

**Comment by Tasssadar** [comment]
Okay. What date do you see in the name of backups you create? Specifically, which year is in there.

Also, if you can, try to get recovery.log - just start TWRP, go to Advanced -> Copy Log to SD Card. Then you should see file recovery.log on your sdcard, upload it somewhere so I can see what is going on in TWRP.

**Comment by qwerty22** [comment]
Full date from log: 2014-01-22 17:48 (real date - 2014-07-03 17:11). Time Zone set to -4
From recovery.log ( https://yadi.sk/d/iU-Ailo5VrZTs ):
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
__bionic_open_tzdata: couldn't find any tzdata when looking for GMT!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
...
E:Cannot load volume /misc!
...
__bionic_open_tzdata: couldn't find any tzdata when looking for AST4ADT!

**Comment by Da-Av** [comment]
TWRP 2.8.0.0 resolved the issue for me. Thanks.
