### ISSUE TITLE
TWRP 2.8.6 is unable to mount encrypted data partition

### ISSUE THREAD

**Issue by DocSniper** [TeamWin/Team-Win-Recovery-Project#323]
TWRP 2.8.3.0 is unable to mount my Data Partition which was encrypted with Android 4.4 (CM 11). The console/log does not show any usable error message.

**Comment by DocSniper** [comment]
Maybe a hint at the console:  encryption header not found

**Comment by BengaloBongali** [comment]
Same here.
CM 11
i9505
2.8.3

**Comment by srt10coupe** [comment]
same here 
cm12
HTC One m7
2.8.3.0 twrp

**Comment by DocSniper** [comment]
No changes with CM12 and TWRP 2.8.4.0

**Comment by srt10coupe** [comment]
the same with me ...

**Comment by JacqylFrost** [comment]
Same issue here. HTC One M8 with GPE custom ROM: http://forum.xda-developers.com/showthread.php?t=2716306

TWRP version 2.8.4.0

Used a pattern lock at first, but I've tried entering as code translated with this:

1 2 3
4 5 6
7 8 9

I've also tried switching to PIN, and even password, I even used cryptfs password: https://play.google.com/store/apps/details?id=org.nick.cryptfs.passwdmanager&hl=en to try and change it, but nothing works.

I'm glad this ROM is stable, because unless I want to factory reset, I'm dead in the water stuck with it for now.

**Comment by DocSniper** [comment]
This modified TWRP does the trick, it can mount/decrypt data successfully:

http://forum.xda-developers.com/lg-g2/development/twrp-twrp-2-8-0-0-kernel-f2fs-tools-t2898705

He wrote this after solving the problem:

"December 27, 2014 (2.8.3.1)
-Tweaked the fstab file
++Changed partition type to ext4 from auto - this should fix broken Format Data / Factory Reset. However, f2fs is still supported. My f2fs cache partition still mounted in twrp even though fstab was set to ext4.
++Added the encrypt partition to the fstab. This should enable twrp to mount encrypted /data partitions. I don't know if this is the problem or not. The one person I asked to try it didn't have any luck. Please others try and let me know if it works or what errors you get. NOTE: An encrypted f2fs /data partition will probably NOT work in this configuration."

**Comment by BengaloBongali** [comment]
I really hope this gets implemented so that I'm not stuck on a nightly anymore...

**Comment by nzgeek** [comment]
I'm seeing this issue on jfltexx with CM12 20150217. I've encrypted my /data partition with a PIN, but TWRP doesn't want to know. Trying to select the partition to mount causes the recovery to hang for a few seconds, buzz, then clear the checkbox.

The log simply says: `E:Unable to mount '/data'`

**Comment by skyzem** [comment]
Same here.
PA 4.6 (Android 4.4)
Galaxy Nexus
2.8.3 and 2.8.5

**Comment by kecksk0enig** [comment]
same here CM12 TWRP 2.8.5.0 on Photon Q 
edit: 
log also says E: Failed to load package '/TWRP/theme/ui.zip'

I am never asked to enter my pin / patternlock

**Comment by marvinandro** [comment]
Add OPO/bacon to the list of can't decrypt under CM12

**Comment by ciaby** [comment]
Same here, OPO with CM12-nightly can't decrypt the /data partition. OPO with CM11 works fine...

**Comment by sahtor** [comment]
Also 2.8.6.0 asks for pattern lock but only 3x3 grid. Any more complex grid 4x4, 5x5, 6x6 is not supported.

**Comment by daks** [comment]
i confirm TWRP 2.8.6.1 only offers 3x3 grid pattern but mine is more complex and i can't enter it.

**Comment by rtherry** [comment]
Any news with 4x4 grid ? Thx

**Comment by overlinden** [comment]
Same at my phone S4 I9505 with CM12.1 nightly 20150623 installed.
Any news when this will be fixed?

**Comment by rtherry** [comment]
is there someone working on 4x4 and more decrypt pattern grid ?

**Comment by Pivert** [comment]
Same problem here, cannot use twrp as my pattern is on 5x5. Did anyone tried to go back to a 3x3 pattern?

**Comment by smarek** [comment]
Seconding this issue, 6x6 lock grid not available in TWRP

**Comment by ShakingHead** [comment]
This is an issue for me with my LG G3/CM12.1 with TWRP 2.8.7.

There appears to be quite a few similar flavours of this issue.  On the LG G3 I don't get a password prompt in TWRP.

**Comment by FSPQR** [comment]
Bump!
TWRP for h815 2.8.7.0 and 2.8.6.1 can NOT decrypt LG G4 H815 #477 
https://github.com/TeamWin/Team-Win-Recovery-Project/issues/477

**Comment by BengaloBongali** [comment]
Mounting and updating CM works for me now with 2.8.7 (Galaxy S4). What I am still not able to do is removing encryption with TWRP. I do factory resets and wipe all partitions (EDIT: and "format data"), but still have to enter my encryption password after a reboot. I solved this with CWM though.

**Comment by Dees-Troy** [comment]
Wipe->Format Data will remove encryption within the TWRP interface.

**Comment by BengaloBongali** [comment]
As I said... It didn't. It says it would, yes. But it didn't.

**Comment by AdamWill** [comment]
2.8.7 still doesn't seem to be able to mount encrypted /data on LG G3 (D852) with CM12.1 nightly 2015-09-03. Logs show:

```
E:Could not mount /data and unable to find crypto footer.
E:Unable to mount '/data'
E:Unable to recreate /data/media folder.
Updating partition details...
E:Unable to mount '/data'
...done
E:Unable to mount storage.
E:Unable to mount /data/media during GUI startup.
Full SELinux support is present.
E:Unable to mount /data/media/TWRP/.twrps when trying to read settings file.
E:Unable to mount '/data'
MTP Enabled
```

There is never a password entry prompt, either at boot or when trying to mount `/data` from the Mount screen. `/system` is not mounted at boot time but can be mounted from the Mount screen.

**Comment by prisriya** [comment]
I am having exactly the same problem as reported above with TWRP 2.8.7 on my Note 2 N7100.
I had encrypted my device. I just rooted and have the above issue when I try to do a backup with TWRP.

Any guidance...

**Comment by Pivert** [comment]
I did workaround the problem by:
- Booting the device, and reduce the pattern to a 3x3.
- Then TWRP properly did ask me the pattern, and properly decrypted the partition.
  Regards,

**Comment by prisriya** [comment]
Thank you. The challenge I am facing - Right now only the Password (High Security) option is enabled.
All the other options - PIN or Pattern have been disabled.
Message: Disabled by administrator, encryption policy or credential storage.
Don't know how to get out of that situation. I used to use this phone earlier for my corporate needs. Since then, I have got rid of my corporate system and hence there's no special enforcement of any policy...

Any guidance on how to get the other options enabled, will help a long way.

**Comment by smarek** [comment]
I've been able to unlock the storage using ADB SHELL, using `adb shell twrp decrypt DECRYPT_CODE`

Java snippet to get DECRYPT_CODE used is here:

```
// file named Pattern.java
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.security.SecureRandom;

public class Pattern {

public static void main(String... args) {

int[] pattern = {DOT_NUMBERS_HERE};
byte[] res = new byte[pattern.length];
for( int i = 0; i < pattern.length; i++ ) {
 res[i] = (byte) (pattern[i]);
}

StringBuffer hexString = new StringBuffer();
for (int i = 0; i < res.length; i++) {
            if ((0xff & res[i]) < 0x10) {
                hexString.append("0"
                        + Integer.toHexString((0xFF & res[i])));
            } else {
                hexString.append(Integer.toHexString(0xFF & res[i]));
            }
        }
    System.out.print("unlock code: ");
    System.out.println(hexString);
}

}
```

Dots are numbered in order like this

```
// 3 x 3
0 1 2
3 4 5
6 7 8

// 4 x 4
0  1  2  3
4  5  6  7
8  9  10 11
12 13 14 15

// 5x5
0  1  2  3  4
5  6  7  8  9
10 11 12 13 14
15 16 17 18 19
20 21 22 23 24

// same goes for 6x6 or larger patterns
```

Write down the dots in order you connect them, so the simple 3x3 pattern (U pattern from top left to top right corner) translates into `0,3,6,7,8,5,2`, put these numbers in code where `DOT_NUMBERS_HERE` is

Then use `javac Pattern && java Pattern` and use the unlock code in `adb shell twrp decrypt DECRYPT_CODE` command

**Comment by AdamWill** [comment]
I think this issue badly needs splitting at least in two. 'twrp doesn't support decryption with patterns other than 3x3' is a _completely_ different bug from `Could not mount /data and unable to find crypto footer.` and no passphrase entry prompt.

**Comment by prisriya** [comment]
Thank you both.
Maybe  I was not clear @smarek 
I actually have a password - not a pattern. Right now I am unable to convert to any other form of protection. All the other options are greyed out. If I understand right the solution that is in the java program is for a pattern. So do not think it will help.

**Comment by smarek** [comment]
@prisriya in fact, if you feed the `int[] pattern` with unicode ids of letters in your password, this solution should work with passwords too

**Comment by smarek** [comment]
storage is not crypted with password in plaintext, but with it's representation in hex strings, basically just convert ASCII letters of your password to HEX representation and use the resulting hex string in command `adb shell twrp decrypt HEX_PASSWORD`

**Comment by prisriya** [comment]
@smarek Thank you. That was super quick. What's the risk I have in trying to do the above. I used to be a developer eons ago, and not any more. Also when putting in the HEX_PASSWORD - how do I need to provide it. e.g. if my password is ABCDE
should I do adb shell twrp decrypt 414243444546 
or
should it be adb shell twrp decrpypt x'414243444546'

May be elementary questions... but still need that help

**Comment by smarek** [comment]
@prisriya well by default, after some amount of testing passwords the crypto can be auto-destructed (resulting in hard reset), i'd suggest you to reload recovery after 2-3 attempts if you don't have backups, use the first command `adb shell twrp decrypt 414243444546`

**Comment by huettenhain** [comment]
Confirming that I have the same problem as @ShakingHead and @AdamWill - down to the error messages posted.

**Comment by bjangelo** [comment]
I believe I have figured out why I am receiving the `Could not mount /data and unable to find crypto footer.` error.  However, I have not yet been fully successful in getting TWRP to decrypt my userdata partition. 

On my device, the LG G3 (D851), the error `Could not mount /data and unable to find crypto footer.` is due to the fact that the crypto blob is stored in a separate partition as opposed to at the end of the userdata partition.  The following shows the fstab from my device during normal boot.

`root@android:/ # grep userdata /fstab.g3`
`/dev/block/platform/msm_sdcc.1/by-name/userdata  /data  ext4  noatime,nosuid,nodev,barrier=1,noatime,noauto_da_alloc,errors=continue  wait,check,encryptable=/dev/block/platform/msm_sdcc.1/by-name/encrypt`

The `encryptable=/dev/block/platform/msm_sdcc.1/by-name/encrypt` options specifies that the crypto blob is stored in the `/dev/block/platform/msm_sdcc.1/by-name/encrypt` partition as opposed to at the end of the userdata partition (i.e. footer).  The fstab file in my TWRP image does not specify that the crypto blob is in a separate partition and uses the default setting, which is to expect the crypto blob to be at the end of the userdata partition.  I was able to fix this issue by modifying the ramdisk in my TWRP image.

I used the following two tools to accomplish this.
- [bbootimg](https://github.com/Tasssadar/libbootimg)
- [abootimg](https://gitlab.com/ajs124/abootimg)

We can unpack the ramdisk from the TWRP recovery image and add the necessary flags to the fstab to specify that the crypto blob is in a separate partition.

`$ mkdir twrp`
`$ cd twrp`
`$ bbootimg -x ../twrp-3.0.0-0-d851.img`
`$ sudo abootimg-unpack-initrd`
`$ sudo vim ramdisk/etc/recovery.fstab`

In the `etc/recovery.fstab` file we need to add `encryptable=/dev/block/platform/msm_sdcc.1/by-name/encrypt` as a flag for the userdata partition.  This is accomplished by adding `flags=encryptable=/dev/block/platform/msm_sdcc.1/by-name/encrypt` to the end of the `etc/recovery.fstab` file.  Now we just repack the TWRP recovery image with the updated ramdisk.

`$ sudo abootimg-pack-initrd initrd.img.new`
`$ bbootimg --create twrp-3.0.0-0-d851.img.new -f bootimg.cfg -k zImage -r initrd.img.new -d dtb.img -m`

Note that you may need to increase `bootsize` in `bootimg.cfg` to compensate for the larger ramdisk.  After flashing this updated TWRP to recovery and rebooting, TWRP does prompt me for the userdata decryption password.

Unfortunately, decryption is still not working properly.  The recovery error I am getting now is `could not find any keystore module`

**Comment by bjangelo** [comment]
A little more progress, but still not complete success.  The `could not find any keystore module` error appears to be due to the fact that `/system` is not mounted and the properties file in my TWRP image is incomplete.  The keystore module is located at `/system/lib/hw/keystore.msm8974.so` for my device.  This library file name is generate from the `ro.board.platform` property.

`$ adb shell getprop ro.board.platform`
`[ro.board.platform]: [msm8974]`

However, when I am booted into recovery, the `ro.board.platform` is not set at all.  I was able to remedy this by once again updating the ramdisk in my TWRP image and adding/updating the following line in `default.prop`.

`ro.board.platform=msm8974`

With this new TWRP image flashed down, I perform the following actions to ensure that `/system` is mounted before attempts are made to decrypt userdata.
1. Cancel the initial data password prompt.
2. Mount /system through the Mount menu.
3. Select Decrypt Data and enter my password.

The error I am receiving now is `could not open keymaster device in keystore (Operation not permitted)`.  This error is coming from the `keystore.msm8974.so` library, which is unfortunately not open source.

**Comment by bjangelo** [comment]
The `keystore.msm8974.so` library relies on `libQSEEComAPI.so` being in the default library search path used by dlopen.  Adding `libQSEEComAPI.so` to `sbin` in the TWRP ramdisk makes this library available to `keystore.msm8974.so`.

Additionally, the modem partition needs to be mounted for the keystore library.  The procedure now is as follows.
1. Cancel the initial data password attempt.
2. Mount /system through the Mount menu.
3. Mount modem partition to /firmware (`# mkdir /firmware && mount /dev/block/mmcblk0p1 /firmware`)
4. Select Decrypt Data and enter password.

The error I am receiving now is `Cannot load dm-crypt mapping table` followed by `Error creating decrypted block device`.

Inspecting the crypto blob for my device in `/dev/block/platform/msm_sdcc.1/by-name/encrypt` reveals that the crypto type is `aes-xts`.  [This](https://github.com/jamesr66a/device_qcom_common_cryptfs_hw/blob/master/cryptfs_hw.c#L166) seems to imply that `aes-xts` means hardware encryption.  Unfortunately, the TWRP image for my device is not compiled with hardware encryption support.  At this time I do not have an Android build system to attempt a TWRP recompile with hardware encryption support.

**Comment by AdamWill** [comment]
This is awesome work, but there's one question that's been bugging me - why did this work up to a certain point then stop working? Did Android transparently re-encrypt things in a different way behind the scenes when we hit a certain CM 12.1 release, or what?

**Comment by bjangelo** [comment]
Maybe at some point the default Android crypto blob storage location switched from being at the end of the userdata partition (i.e. footer) to a separate partition?  I haven't looked into the decision logic between userdata footer and a separate partition for the crypto blob.

The hardware encryption issue appears to just be due to a TWRP build mis-configuration for my device.

**Comment by arcane47** [comment]
@bjangelo I'd be interested to hear of you were successful in mounting the encrypted drive. Same partition structure on my end. I'm not sure the best way to wipe the encryption, but I have manage to dd /dev/zero over the encrypt partition.

**Comment by bjangelo** [comment]
@arcane47 I am currently unable to mount the encrypted drive in TWRP because the data partition is encrypted with hardware disk encryption but the TWRP image for my device (LG D851) has not been compiled with CONFIG_HW_DISK_ENCRYPTION.  Unfortunately I do not have access to an Android build machine but, if I was able to obtain a TWRP image for the D851 compiled with CONFIG_HW_DISK_ENCRYPTION, I believe I would be able to mount the encrypted drive.

I have not tried removing encryption but, as far as I know, fs_mgr should not attempt to mount data as an encrypted partition if the "encryptable=" option is removed from the fstab file (boot and recovery).

**Comment by ghost** [comment]
**E: Could not mount /data and unable to find crypto footer.** on Mi4 with TWRP 3.0.0.0 and Android 6

**Comment by gabika1941** [comment]
same on Redmi 2 "enhanched" (2GB RAM, 16GB storage). It somehow started an encryption, i don't know how, i didn't want to encrypt anything. Now I can boot recovery, and fastboot, but I can't format or mount /data and /cache, I can't flash with fastboot, because it can't write to the partition.

**Comment by ghost** [comment]
@gabika1941 try with fastboot and [Mi PC Suite](http://en.miui.com/thread-92720-1-1.html) to flash the [ROM](http://en.miui.com/download-261.html)

**Comment by gabika1941** [comment]
@EniGMist4 it says "Try connect in normal mode first then switch"

**Comment by overlinden** [comment]
I just updated TWRP to version 3.0.0.0. and it sucessfully detects the encrypted partition and mounted it. Great work. :)

**Comment by ghost** [comment]
@overlinden which Phone?

**Comment by overlinden** [comment]
@EniGMist4 I use a GT-9505 with CyanogenMod 12.1-20151217-NIGHTLY-jfltexx

**Comment by ghost** [comment]
I think that MIUI rom have a different implementation of encryption, because TWRP is not able to mount encrypted partition

**Comment by gabika1941** [comment]
there was Cyanogenmod 12.1 on it. but nevermind, i've already sent the phone to repair. i ran out of ideas about it.

**Comment by snowdream** [comment]
Any solution?

**Comment by tscmacdonald** [comment]
@smarek I've just tried to run your code snippet on a 4x4 pattern, but it fails with
`error: integer number too large: 121384127111415
int[] pattern = {121384127111415}`

Unfortunately, I know almost nothing about Java. Any help would be desperately appreciated.

**Comment by smarek** [comment]
@tscmacdonald define pattern like this, separate numbers with commmas ;)
```
int[] pattern = {12,13,8,4,12,7,11,14,15}
```

**Comment by bigbiff** [comment]
Encryption is per device. Can't debug all devices in one issue.
