### ISSUE TITLE
TWRP 2.8.3.0 victara loosing settings on reboot

### ISSUE THREAD

**Issue by hkorth** [TeamWin/Team-Win-Recovery-Project#326]
TWRP 2.8.3.0 on victara (Moto X) does not retain the settings (e.g., time zone, backup selection) between reboots. Conversely, TWRP 2.8.0.1 remembered the previous recovery settings properly. A fix is much appreciated. Happy to provide further input if needed.

**Comment by ghost** [comment]
Same here on my Galaxy S5. As soon as you reboot (in flightmode to disable time sync through the mobile network) the date is set to today -3 days and the time is set to now + 2 hours.
This causes several issues with widgets being off and errors in WhatsApp ("Your phone date is inaccurate" warning).
Because you stated that 2.8.0.1 was working for you I installed that version, but it's not working for me either...
