### ISSUE TITLE
LG G3 (d855) - Unable to locate '/modem' partition for backup calculations

### ISSUE THREAD

**Issue by janssenb** [TeamWin/Team-Win-Recovery-Project#328]
E: Unable to locate '/modem' partition for backup calculations

Backing up Boot...
Backing up System...
Backing up Data...
Backing up Cache...
E: Unable to locate '/modem' partition for backup process.
Backing up EFS...
Backing up efs2...
Updating partition tables
...done
[BACKUP COMPLETED IN 124 SECONDS]

Any idea why the modem partition is not being backed up...?
Version 2.8.3.0

**Comment by wulsic** [comment]
In the G3 device tree there is the fstab file, If you look into the fstab file there is no /modem defined, maybe in other upto date device tree's there is it but it could also be included in efs2 maybe.

**Comment by janssenb** [comment]
/dev/block/platform/msm_sdcc.1/by-name/modem /firmware  <--- ? 

It is defined.. and my modem is mounted as "/firmware"..

**Comment by wulsic** [comment]
Watch the recovery.fstab file, I said it before wrong it wasn't defined as /modem but /radio it is pretty logical actually after I see this because it's kinda the same thing.
See these commits also regarding to the modem backup:
https://github.com/777jon/android_device_lge_g3-common/commits/f6b7e79ddf6776eac05ba45de0a5deebfa07d748/recovery.fstab

If you are going to compile twrp for your G3, then I suggest to use his source or that from somebody else which also includes the latest fixes for the G3 recoveries until TeamWin updates their sourcecode.
