### ISSUE TITLE
TWRP  V2.8.4.0 backup fails on Moto G (falcon)

### ISSUE THREAD

**Issue by thenextdon13** [TeamWin/Team-Win-Recovery-Project#335]
Hello-
I just installed TWRP  V2.8.4.0 on my Falcon Moto G.

Backups fail every time - found while attempting to do backup prior to making major system modifications.

Fails regardless of checkboxes for md5sum creation and compression.
At beginning there are a number of lines indicating that 'Unable to stat' (all of which are in /data/dalvik-cache)
System backup passes and md5sum creation passes.
Backing up Data fails with no errors other than 'Backup Complete : Failed'

This occurs both before and after a 'wipe' from the TWRP menu.

**Comment by Dees-Troy** [comment]
Most likely you have a corrupt data partition which can only be fixed by formatting data. You can try to repair it by going to Wipe, select only the data partition, tap on the Repair or change file system button, then Repair. Most likely that won't fix it though and you will have to do a Format Data (Wipe -> Format Data, type yes and hit enter). This will delete all of your apps and everything on your internal storage.

**Comment by thenextdon13** [comment]
You were correct, in both of your above assumptions.
Fix did not work, Wipe -> Format did.

many thanks for the help!
