### ISSUE TITLE
TWRP 2.8.5.0 on Galaxy S5. Can`t set the correct Time Zone.

### ISSUE THREAD

**Issue by qwerty22** [TeamWin/Team-Win-Recovery-Project#346]
TWRP 2.8.5.0 on Galaxy S5 G900F. I can not set the correct Time Zone UTC +3.

Reproduction:
1. Setup stock recovery.
2. Setup TWRP 2.8.5.0 - openrecovery-twrp-2.8.5.0-gt-klte.tar.md5.
3. Try to set Time Zone.

**Comment by qwerty22** [comment]
__bionic_open_tzdata: couldn't find any tzdata when looking for localtime!
...
I:Set page: 'settings'
I:Set page: 'timezone'
__bionic_open_tzdata: couldn't find any tzdata when looking for WST-4!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!
__bionic_open_tzdata: couldn't find any tzdata when looking for SAUST-3!
__bionic_open_tzdata: couldn't find any tzdata when looking for posixrules!

**Comment by Dees-Troy** [comment]
The errors showing in the log don't impact the ability to set the time zone. That's an error that shows up in all recoveries due to the way that Google programmed libc in AOSP's bionic. The libc source code is built and used by TWRP but libc source isn't part of TWRP so we have no plans to fix the error message. We could fix it by including the tzdata file in recovery, but the tzdata file is rather large and won't fit in the recovery partition of some devices.

**Comment by qwerty22** [comment]
Ok, I got it, the errors showing in the log don't impact the ability to set the time zone. But I can`t set the correct time zone. How do I set the correct time zone?
