### ISSUE TITLE
unzip missing in hammerhead 2.8.6.0

### ISSUE THREAD

**Issue by rapperskull** [TeamWin/Team-Win-Recovery-Project#367]
Supersu 2.47 introduced a bad recovery check: the new installer checks the existence of /sbin/unzip and fails if it's not present.
Unfortunately unzip is not present in TWRP 2.8.6.0 on hammerhead.
Can you please fix this?

**Comment by huckleberrypie** [comment]
Not sure if this will be addressed as there's an option for embedding a SuperSU installer within TWRP, but it would be 'swell if this issue is fixed somehow.

Been getting this upon trying to install the latest SuperSU zip on my Galaxy S7 clone. Thought I screwed up somehow upon trying to compile my own recovery, but it looks like I'm not alone with this. :/

**Comment by bigbiff** [comment]
Supersu is unsupported now.
