### ISSUE TITLE
Unable backup to external SD card (MicroSDXC 64gb class10 formatted to exFAT)

### ISSUE THREAD

**Issue by vanowm** [TeamWin/Team-Win-Recovery-Project#37]
Attempt switching to external card immediately switches it back to internal.

**Comment by vanowm** [comment]
It seems the problem is not the card type, but the format.
TWR doesn't support exFAT.

Samsung SG3 formats sd cards into exFAT

**Comment by Dees-Troy** [comment]
exFAT probably won't ever make it into the Linux kernel due to the more restrictive nature of the licensing that Microsoft has applied to that file system. As such, you probably won't ever see it supported in any recovery. You can format to FAT or ext4 (though you'll have a different set of problems with ext4).

**Comment by vanowm** [comment]
I wonder if there is a way have multiple partitions on sdcard? For instance keep 10gb exFAT for large files and the rest in FAT? Would TWRP support that?
