### ISSUE TITLE
2.8.6.0: Copy Log to SD - Wrong Directory

### ISSUE THREAD

**Issue by hendricksond** [TeamWin/Team-Win-Recovery-Project#402]
In previous versions, the Copy Log to SD feature would copy the recovery.log to /external_sd/recovery.log. However, on 2.8.6.0 for jfltetmo (T-mobile Galaxy S4), it is copying the recovery.log to /data/media/

I:operation_start: 'Copy Log'
I:Can't probe device /dev/block/mmcblk0p29
E:Unable to mount '/data'
I:Actual block device: '/dev/block/mmcblk0p29', current file system: 'ext4'
I:Copying file /tmp/recovery.log to /data/media/recovery.log
Copied recovery log to /data/media.

This fails, because TWRP is unable to mount my encrypted data partition (issue #304). Workaround was to use adb to pull /tmp/recovery.log.

**Comment by joeykrim** [comment]
Can you specific which previous version worked and paste the recovery output showing the exact path it copied to?

**Comment by hendricksond** [comment]
It worked in 2.8.0.1.

 I:Copying file /tmp/recovery.log to /external_sd/recovery.log

If you want to see a full log from that version, it's here: http://pastebin.com/VDe5j9Ar

**Comment by Dees-Troy** [comment]
The destination of the copy log function is based on the currently selected storage location. This is the same storage location used for backups and to determine the initial path for zip selection, etc. The use of the current storage is by design, so TWRP is working as intended:
https://github.com/omnirom/android_bootable_recovery/blob/android-5.1/gui/action.cpp#L646

**Comment by hendricksond** [comment]
Got it. I didn't realize storage location was being reset on every boot, due to TWRP being unable to save its settings to data as a result of its failure to decrypt.
