### ISSUE TITLE
Unknown Baseband after flashing on 2.3.0.0

### ISSUE THREAD

**Issue by Joecascio2000** [TeamWin/Team-Win-Recovery-Project#49]
After upgrading to 2.3.0.0 after every ROM flash I get "Baseband Unknown" in About Phone. This has been confirmed by other users as well and on different ROM flashes.

A simple reboot fixes the problem, although I haven't confirmed it for myself.

[Samsung Galaxy Nexus - Maguro - 4.1.2]

You can find more info here http://forum.xda-developers.com/showthread.php?t=1592689&page=44 and start at post 431.

**Comment by ppog** [comment]
Same here. reboot fixes it. But then at the next reboot after that the problem returned for me, without ever going into recovery.

**Comment by ppog** [comment]
I didn't think to check it myself, but another user on the Paranoid Android GSM thread on xda said that when it boots and says there is no baseband it also shows no IMEI when *# 06# is typed in the dialer

**Comment by iNSiGhT59** [comment]
ppog is talking about me... 

I just flashed the 4.1.2 factory image and at some boot, i'm still having the baseband/IMEI issue... 

Dunno where is the problem... 
The efs partition shouldn't be totally corrupted, otherwise this issue should happen at every boot... 

What is sure is that the problem persist after a factory image flash... 

So, the question is : what have we to do to get rid of this issue, definitively...

**Comment by Dees-Troy** [comment]
I'm going to leave this issue open for now, but near as I can tell it is not a TWRP issue and probably related to the recent 4.1.2 release of Android for the GSM GNex.

**Comment by Dees-Troy** [comment]
Other users have reported getting the same error on CWM. I don't own a GSM Gnex and since it doesn't appear to be TWRP specific I have decided to close this issue.
