### ISSUE TITLE
[OnePlus X] compile with crypto modules w/ OOS 2.1.2 

### ISSUE THREAD

**Issue by moutonjr** [TeamWin/Team-Win-Recovery-Project#535]
Hi, 

After the unofficial release of TWRP for OnePlus X (see thread http://forum.xda-developers.com/oneplus-x/orig-development/recovery-twrp-2-8-7-0-touch-recovery-t3252840) by Qasar and hd2o, the image fails to mount encrypted systems on OxygenOS 2.1.2.

I made a post on XDA about this topic : http://forum.xda-developers.com/general/help/twrp-update-encryption-t3265995:

When booted in TWRP : 
~ # twrp decrypt 002932839239230
Attempting to decrypt data partition via command line.
E:No crypto support was compiled into this build.

I tried to install new firmware OOS 2.1.3, so I tried without decrypt device : (ADB)
~ # twrp install /external_sd/uc.zip
E:Unable to mount '/data'
command is: 'decrypt' and there is no value
E:No password provided.
Done processing script file

Is it possible to build [1] a version with the right crypto lib attached ?

**Comment by Dees-Troy** [comment]
It'd be possible to build a version with crypto support if you have device configs. Because the device doesn't have official support, we don't have device files in our repos, but maybe the person who published the OnePlus X TWRP has proper device files for it. You may find the information in this issue useful because the same issues with initializing the keymaster will apply to the X as well:
https://github.com/TeamWin/android_device_oneplus_oneplus2/issues/1
