### ISSUE TITLE
Fix Permissions Crashes - HTC One X (Evita)

### ISSUE THREAD

**Issue by maxamillion** [TeamWin/Team-Win-Recovery-Project#57]
When I select Advanced -> Fix Permissions and slide to confirm, it will appear to begin running but then (I assume) crash and go back to the main menu. I have posted both recovery.log and packages.xml as per Dees_Troy and my irc conversation. They are available below:

recovery.log - https://paste.tinyw.in/index.php/view/20565178
packages.xml - https://paste.tinyw.in/index.php/view/22448325

Thank you,
-AdamM

**Comment by Dees-Troy** [comment]
I should have looked at this sooner, but it appears that packages.xml is cut off somewhere at the end. I don't know if you didn't paste the whole file correctly or if the XML file somehow got corrupted / damaged on the device but that appears to be the problem.

I do know that we need to update our code to better handle problems with the XML though so that it can fail gracefully instead of crashing.

**Comment by maxamillion** [comment]
https://www.dropbox.com/s/1cec6jpkd1af3ud/packages.xml

**Comment by bigbiff** [comment]
Hi, I was able to parse your packages.xml with no problems. Is this still happening for you?

**Comment by maxamillion** [comment]
It is, is there a specific version I should be trying with?

**Comment by bigbiff** [comment]
Whatever is the latest for your device.

**Comment by maxamillion** [comment]
Yes, it appears 2.3.3.1 has resolved the issue. Thank you, Closing.
