### ISSUE TITLE
Cant boot into bootloader from TWRP

### ISSUE THREAD

**Issue by TheViper** [TeamWin/Team-Win-Recovery-Project#65]
When I select "reboot into bootloader" in twrp it just reboots the whole system, it wont boot into bootloader

HTC One S, 1.14 hboot, tmobile, running trickdroid V7, rooted

**Comment by Dees-Troy** [comment]
I think I've seen your posts on XDA about this issue and near as I can tell the issue is specific to your device. Others with the same kind of devices don't have this issue. There's really nothing that we will be able to do within TWRP to solve this issue. Sorry. At best I could disable / hide the button for rebooting to bootloader, but since it's working for others I'd rather not do that.

**Comment by TheViper** [comment]
Ok, thanks for getting back to me
