### ISSUE TITLE
Require Pattern/PIN

### ISSUE THREAD

**Issue by f0rki** [TeamWin/Team-Win-Recovery-Project#66]
A nice feature of a recovery would be that the recovery prompts the user for a password/pin/(pattern) before allowing _any_ action. This would improve security of a modded device, since if it is lost nobody can easily install some kind of rootkit to the phone and grab all the data.

I guess there are several ways:
1. mount /system and check against android OS pin/password/pattern
would be the most flexible and user-friendly way, but might be hard to do. especially if the user has set a pattern. But what to do when no android is present or the user has set nothing? 
2. add password/pin to recovery image before flashing
seems like a really dirty hack...
3. allow setting password/pin in recovery
where to store it? mounting /system and saving it somewhere there? Also seems kind of dirty.

I realize that is a lot of work. Any chance this will be implemented?

**Comment by Dees-Troy** [comment]
All someone would have to do is flash a different recovery that doesn't check for or use the password/pin system to get at your data. The cold hard truth is that most devices are a simple fastboot or Odin flash away from being insecure again no matter what we try to do. You can argue all that you want, but at best a password locked recovery would just offer superficial security at best. Part of the reason that I don't want to add this kind of feature is because I don't want people lulled into a false hope or belief that they are secure when they really aren't. If you want to secure your data, you will have to use Android's whole device encryption. While a thief would still be able to wipe your data away, they wouldn't be able to access your data.

**Comment by f0rki** [comment]
Afaik some devices allow you to relock your bootloader, which would make this feature not as pointless. Then an attacker couldn't just flash another recovery or boot another kernel to gain access to the data. 
I'm not sure this is really working, but I though of it like this:
- unlock bootloader, device wiped
- flash custom recovery and custom ROM
- relock bootloader --> recovery and kernel cannot be changed anymore
- possible to update android via recovery

You'd still have to backup, unlock, flash, relock for each recovery and kernel update, but this doesn't happen that often.

Androids encryption prevents an thief from accessing your data, but doesn't protect you against someone who installs some kind of rootkit on your device and gives it back to you. (assuming you have an unlocked bootloader or a custom recovery)

**Comment by mirh** [comment]
[Well](https://twrp.me/faq/securetwrp.html), my phone has usb port disabled. It just works for charging by now. 

It really wouldn't hurt to have password protection even for the last hole in security.
