### ISSUE TITLE
Change cryptfs password from twrp

### ISSUE THREAD

**Issue by 0xded093** [TeamWin/Team-Win-Recovery-Project#682]
Hi, I can't boot my oneplus, when I try to enter my password at boot the phone crash while I'm writing (after 3-4 seconds) and I can't do anything.
TWRP decrypt correctly data partition, I was wondering if it's possible to change the encryption password from recovery,  to change it with something shorter so I have time to write it and boot the system (I know seems crazy).

I tried with "vdc cryptfs" utlity but it gives me an error.

**Comment by llucax** [comment]
I find myself needing this feature too. I flashed a ROM that has a problem with asking for password at boot, and I accidentally enabled that feature so now the device wont boot, but I have full access to TWRP and can decrypt the device there.

**Comment by cmarquezrusso** [comment]
+1 Using TWRP 3.0.2-0 

Issue: Android asking for a PIN  but Im using a password. I am trying to change my encryption password to a pin

Recovery adb 
```
/sdcard # cryptfs
/sbin/sh: cryptfs: not found
/sdcard # vdc
/sbin/sh: vdc: not found
```

```
# mount
rootfs on / type rootfs (rw,seclabel,size=1301000k,nr_inodes=325250)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,size=1379028k,nr_inodes=344757,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,seclabel,relatime,size=1379028k,nr_inodes=344757)
pstore on /sys/fs/pstore type pstore (rw,seclabel,relatime)
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
/dev/block/sda13 on /cache type ext4 (rw,seclabel,relatime,data=ordered)
/dev/block/dm-0 on /data type ext4 (rw,seclabel,relatime,data=ordered)
/dev/block/dm-0 on /sdcard type ext4 (rw,seclabel,relatime,data=ordered)
```

```
[...]
I:Set page: 'trydecrypt'
I:operation_start: 'Decrypt'
crypt_ftr->fs_size = 52453304
Using scrypt with keymaster for cryptfs KDF
Trying to convert ascii string of odd length
Failed to convert passwd from hex, using passwd instead
keymaster module name is Keymaster QTI HAL
keymaster version is 256
Found keymaster1 module, using keymaster1 API.
Signing safely-padded object
Using scrypt with keymaster for cryptfs KDF
Trying to convert ascii string of odd length
Failed to convert passwd from hex, using passwd instead
keymaster module name is Keymaster QTI HAL
keymaster version is 256
Found keymaster1 module, using keymaster1 API.
Signing safely-padded object
crypt_ftr->fs_size = 52453304
Using scrypt with keymaster for cryptfs KDF
keymaster module name is Keymaster QTI HAL
keymaster version is 256
Found keymaster1 module, using keymaster1 API.
Signing safely-padded object
Using scrypt with keymaster for cryptfs KDF
keymaster module name is Keymaster QTI HAL
keymaster version is 256
Found keymaster1 module, using keymaster1 API.
Signing safely-padded object
load_crypto_mapping_table: target_type = req-crypt
load_crypto_mapping_table: real_blk_name = /dev/block/sda14, extra_params = fde_enabled ice
Password did not match but decrypted drive mounted - continue
```

**Comment by Dees-Troy** [comment]
The ability to change the password for decrypt from TWRP would be dangerous as we have no control over the firmware installed on the device and no way to ensure compatibility. An incompatible password change could result in a total loss of data.

**Comment by nyanpasu64** [comment]
yeah... right now my device is convinced my password does not exist, yet is correct, and my data is corrupt. Despite it being able to decrypt via TWRP (entering PIN as a numeric password).

And due to your "holier-than-thou" attitude prohibiting changing your password from TWRP, my device is unusable. Every time I boot (not in TWRP) it thinks my data is corrupt and offers to reset. And if not for you @Dees-Troy, I could run `cryptfs changepw` in TWRP to change the password to `default_password` (which Android likely thinks it is).

And you're also partly responsible for the LG G2 I killed several years ago. There was no valid boot-time password (I didn't know about `default_password`).  TWRP was missing cryptfs, so I flashed a buggy recovery which ended up overheating the phone and partly melting my display cable, creating black lines on-screen.

--------------

In all likelihood, cryptfs_get_password_type() is returning crypt_ftr.crypt_type=CRYPT_TYPE_DEFAULT. In the absence of TWRP, how exactly do you propose I find the right 4 bytes in my filesystem to change to CRYPT_TYPE_PIN?

**Comment by digitalcircuit** [comment]
Despite being many, many months late, in case it helps others:

I've run into this issue, and it actually turns out that Android still knew I was using a pattern.  However, the cryptfs flag `CRYPT_DATA_CORRUPT` got set despite the data not actually being corrupt.  TWRP ignores this, hence being able to decrypt just fine, but Android listens to that flag, refusing to try to decrypt.

Based on [`cryptfs.h` in LineageOS 15.1](https://github.com/LineageOS/android_system_vold/blob/0c8dc2251a7c0b3bcb50c39734f7b9503358b4d2/cryptfs.h ), you need to change the 12th through 16th bytes in the metadata section to zero, to remove all flags (**don't do this** if it's anything other than `8`, `CRYPT_DATA_CORRUPT`).

**For the Nexus 6**, [based on `fstab.shamu`'s `encryptable=/dev/block/[something]` lines](https://github.com/LineageOS/android_device_moto_shamu/blob/lineage-15.1/rootdir/etc/fstab.shamu#L10-L11 ):
1. ADB in recovery (e.g. TWRP), pull all `/data` files you care about, making a backup on your computer.
2. ADB in recovery: `dd if=/dev/block/platform/msm_sdcc.1/by-name/metadata of=/sdcard/metadata.img`
3. ADB pull `metadata.img`
4. Hex-edit `metadata.img`, checking bytes 12-16.  There should only be an `8`.  If so, set the 12th-16th bytes to zero.  Save the file as `metadata-flags-cleared.img`.  If it's anything else, **stop**, you might further corrupt your data partition.
5. ADB push the modified `metadata-flags-cleared.img` back,
6. ADB in recovery (e.g. TWRP): `dd if=/sdcard/metadata-flags-cleared.img of=/dev/block/platform/msm_sdcc.1/by-name/metadata bs=1 count=16`

Reboot, and it should hopefully work.

**NOTE:** If your device specifies `metadata=footer`, then your cryptfs metadata is stored near the end of the userdata partition.  You'll have to [follow the `cryptfs.cpp` logic](https://github.com/LineageOS/android_system_vold/blob/0c8dc2251a7c0b3bcb50c39734f7b9503358b4d2/cryptfs.cpp#L613-L633 ) to make an image using dd with the right offsets.  Proceed very carefully; you could easily fully corrupt your data.

Useful cryptfs metadata debugging tool: https://github.com/santoku/Santoku-Linux/blob/master/tools/android/android_bruteforce_stdcrypto/bruteforce_stdcrypto.py

**Comment by digitalcircuit** [comment]
Last addendum: I've filed a new issue suggesting [TWRP should detect and warn about the `CRYPT_DATA_CORRUPT` flag, including the code changes necessary to do this](https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1509 ).
