### ISSUE TITLE
Reset to factory version 

### ISSUE THREAD

**Issue by ghost** [TeamWin/Team-Win-Recovery-Project#754]
I wanted to give my dad my Samsung Galaxy s4 mini and therefore wanted to reset it to factory version. Done this on many phones. However with this one a blue colored menu called team win recovery project pops up and there's no way to get out of it. Several phone stores here have tried to help but no one knows about this and have never seen that issue before. Now I'm here have created an account because emails are never answered, the team win informs. I'm pretty frustrated here. Is this a virus?? And what are you doing on my phone? I've resented loads of phones and have never ever seen this before.

**Comment by Dees-Troy** [comment]
http://lmgtfy.com/?q=S4+mini+return+to+stock

Seriously... some people....

**Comment by ghost** [comment]
No one here from any company have seen such thing on the phone when wanting to reset it to factory version! I have to know how to get rid of the spam program? I have NOT downloaded whatsoever called TeamWinRecoveryProject! I have set previous smartphones back to factory-version, and it was very easy. I contact you to know what to do as it is your program making the issue on my phone. I expect some help here! my phone is ruined.

**Comment by kotzir** [comment]
Oh, oh, oh calm dude. 1st of all your phone is not ruined. TWRP recovery is a custom android recovery to flash AOSP and in general unsigned zips on phones. I would like to inform you that TWRP recovery is not a virus at all, and mainly it CAN'T be installed by itself. Someone did install it, so ask those who "played" with your device or used it, instead of blaming anyone from this team. Finally to give you an answer on how to fully restore your device back to fully stock firmware and recovery, the one recovery you are familiar with, go to http://www.sammobile.com/firmwares/, type the model number and download the latest firmware for your region. You will find instructions there too. You will have to use a program called odin. It works on windows.

**Comment by ghost** [comment]
Okay, I will for sure go back to the store in Norway where I bought the phone. I got it cheaper because one dude regretted the the buy, but only one day after. So in this time this dude must have installed your programe...... Theres no other way. As I have no knowledge on technical issues on how to do all such things = being seriously dumb on such things, I will regard this as phone lost. Thanks for the answer, and answering back, so to speak. I will unsubscribe from your site.
