### ISSUE TITLE
Not restoring

### ISSUE THREAD

**Issue by gokart2** [TeamWin/Team-Win-Recovery-Project#8]
Evo 3d cdma, twrp 2.1. Before and after hboot downgrade (hboot 1.5 and 1.4).  Same story both times....made a new backup. Ran a different rom. Tried restoring that last backup and it acts as if if flashed the backup instantly, right after u click restore it's done. Nothing changes. The backups show data and Mb's.  Tried multiple wiping methods and scripts. It basically says it restored instantly, but it didn't actually do anything.

**Comment by Dees-Troy** [comment]
This issue has been identified and fixed in the cm9wip branch.  Whenever we release a new version then it will be gone.  The issue appears if you hit the refresh sizes button before doing a backup.  Until we ship a new version, either don't use the refresh sizes button or watch the console output.  The backup is still running in the background and you can wait for it to finish.
