### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by NeoBeum** [TeamWin/Team-Win-Recovery-Project#876]
When using the terminal, if attempting to erase characters that have wrapped to new line, the cursor creates a new line with each backspace keypress, and concatenates the remaining characters of the line

Example:

rm /system/media/audio/rin
||gtones/*.ogg                                     || -Cursor position just before the G, and backspace to the line above

> rm /system/media/audio/rin |cursor here||wraps here| 
>   (empty spaces) (empty spaces)                                 gtones/*.ogg
>   (empty spaces)   gtones/*.ogg 
>                                 gtones/*.ogg

Sorry for shit diagram... couldn't capture the screen

**Comment by that1** [comment]
I can reproduce this. I guess I need to research how line wrapping is supposed to work.

**Comment by nailyk-fr** [comment]
step to reproduce: write [something](https://cloud.githubusercontent.com/assets/16372405/23877842/9bbe7438-0844-11e7-95b3-8d38b8999c0f.png) until line wrap. Move cursor on the first line, use [backspace](https://cloud.githubusercontent.com/assets/16372405/23877843/9bbfdfd0-0844-11e7-9e02-0f55009e85ab.png) (here I remove the 'tt'). 

For information the backspace correct is correctly applied. AFAICT this issue was present on earlier versions.

**Comment by that1** [comment]
This should fix it -> https://gerrit.omnirom.org/#/c/22369/

**Comment by NeoBeum** [comment]
Cool thanks,
This will make it easier for me to try and work out why recovery is failing for the Z5C

**Comment by nailyk-fr** [comment]
[1](https://cloud.githubusercontent.com/assets/16372405/24013125/b52cea10-0a80-11e7-9261-67f31b8ca7ff.png) [2](https://cloud.githubusercontent.com/assets/16372405/24013126/b556838e-0a80-11e7-92d7-fa45d1fa8b10.png)
As usual @that1 perfect fix.Thanks!

**Comment by NeoBeum** [comment]
been added to the main git now I think
